### DISCUSSION TITLE
Installing Tandoor for dummies

### DISCUSSION THREAD

**Discussion by tomtjes** [TandoorRecipes/recipes#1161] [Q&A] [answered]
I had zero experience with docker, so as a total dummy\* it took me a while to figure things out. Here's how I finally managed to install Tandoor. Hopefully this will make it more accessible for others.

\* So, take it with a grain of salt. No guarantee that this is actually a best practice...

- Create server with docker (pre-)installed
- point at least one `mydomain.com` and one `mysubdomain.mydomain.com` to server IP
- ssh into server
- `cd /opt`
- `mkdir recipes`
- `cd recipes`
- `wget https://raw.githubusercontent.com/vabene1111/recipes/develop/.env.template -O .env`
- `base64 /dev/urandom | head -c50` and copy the result
- `nano .env`
  - paste key from above
  - enter a Postgres password
  - exit and save
- `cd /opt`
- Install docker compose: https://docs.linuxserver.io/general/docker-compose
    - `sudo curl -L --fail https://raw.githubusercontent.com/linuxserver/docker-docker-compose/master/run.sh -o /usr/local/bin/docker-compose`
    - `sudo chmod +x /usr/local/bin/docker-compose`
- `nano docker-compose.yml`
  - paste and edit domains/subdomains
```
---
version: "2.1"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=mydomain.com # <---- edit this
      - SUBDOMAINS=mysubdomain,myothersubdomain # <---- edit this
      - EXTRA_DOMAINS=myotherdomain.com # <---- edit this
      - VALIDATION=http
    volumes:
      - /home/aptalca/appdata/swag:/config
      - /opt/recipes/media:/media
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  db_recipes:
    restart: always
    container_name: db_recipes
    image: postgres:11-alpine
    volumes:
      - ./recipes/db:/var/lib/postgresql/data
    env_file:
      - ./recipes/.env

  recipes:
    image: vabene1111/recipes
    container_name: recipes
    restart: unless-stopped
    env_file:
      - ./recipes/.env
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./recipes/static:/opt/recipes/staticfiles
      - ./recipes/media:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
```
  - exit and save
- `docker-compose up -d`
- `cd /home/aptalca/appdata/swag/nginx/proxy-confs/`
- `cp recipes.subdomain.conf.sample recipes.subdomain.conf`
- `nano recipes.subdomain.conf`
  - change line `server_name recipes.*;` to `server_name mysubdomain.*;`
  - exit and save
- `cd /opt`
- `docker-compose up --force-recreate --build -d`
- go to `https://mysubdomain.mydomain.com` (if you get a "502 Bad Gateway" error, be patient. It might take a short while until it's functional)
