### DISCUSSION TITLE
LDAP not working

### DISCUSSION THREAD

**Discussion by jens-234** [TandoorRecipes/recipes#1519] [Q&A]
Hi everybody,

I'm trying to use LDAP as authentication backend. Unfortunately it's not working for me.

I have already configured many different applications to authenticate against my LDAP servers. So I should be able to supply the right values. But I'm unable to find the reason for it not working here.

This is an excerpt from my .env file:

```
LDAP_AUTH=1
AUTH_LDAP_SERVER_URI=ldap://dc1.subdomain.domain.tld:389/
AUTH_LDAP_BIND_DN=CN=SOMEUSER,CN=Users,DC=subdomain,DC=domain,DC=tld
AUTH_LDAP_BIND_PASSWORD=SOMEPASSWORD
AUTH_LDAP_USER_SEARCH_BASE_DN=CN=Users,DC=subdomain,DC=domain,DC=tld
```

SOMEUSER, SOMEPASSWORD and the domain names are of cause just placeholders here.

Judging by the documentation and this page: https://github.com/TandoorRecipes/recipes/blob/develop/.env.template
....my file looks ok.

Until I manage to get LDAP connections to work in cleartext, I always leave encryption disabled for the config phase. It would just be another source of problems.

I've had a look at these posts already:
https://github.com/TandoorRecipes/recipes/discussions/1225
But the log file stays empty for me unfortunately.

Doesn't help either: https://github.com/TandoorRecipes/recipes/discussions/1299

@lostlont By any chance might you be able to help here?

**Comment by smilerz** [comment]
can you please enable DEBUG and supply the log from tandoor?

**Comment by jens-234** [comment]
I already enabled that earlier, but it doesn't seem to be very verbose.

```
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/css/app.min.css HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/js/jquery-3.5.1.min.js HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/js/bootstrap.min.js HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/js/popper.min.js HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/css/select2.min.css HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/js/select2.min.js HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/css/select2-bootstrap.css HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/themes/select2-bootstrap-theme.css HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/fontawesome/fontawesome_all.min.css HTTP/1.0" 304 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/themes/tandoor.min.css HTTP/1.0" 200 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/assets/brand_logo.png HTTP/1.0" 200 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
someIP - - [09/Feb/2022:23:06:32 +0100] "GET /static/assets/favicon.svg HTTP/1.0" 200 0 "http://linux14/accounts/login/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
```

Or is this an indicator that the env file isn't really used?

**Reply by smilerz** [reply]
ugh - logging isn't enabled for LDAP.  I pushed a PR, but it won't hit the release version for a week or so

**Comment by jens-234** [comment]
I guess I can wait another week. Just installed everything, but didn't want to start using it with local accounts.

**Reply by smilerz** [reply]
someone else might be able to help - i've just never set it up

**Reply by lostlont** [reply]
The settings you have should be fine. Is this a Docker setup? If so, are you sure your container can reach the LDAP server at this URI?

**Comment by jens-234** [comment]
Yes, it's in docker.

Good point, I had only tested that connectivity from the docker host. But in the end it turns out fine as far as I can tell:

```
root@linux14:~# ping dc1.mydomainname.org
PING dc1.mydomainname.org (mySubNet.2) 56(84) bytes of data.
64 bytes from dc1.mydomainname.org (mySubNet.2): icmp_seq=1 ttl=128 ti                                                                             me=1.07 ms
64 bytes from dc1.mydomainname.org (mySubNet.2): icmp_seq=2 ttl=128 ti                                                                             me=0.384 ms
^C
--- dc1.mydomainname.org ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 0.384/0.725/1.067/0.341 ms

root@linux14:~# su - tandoor
tandoor@linux14:~$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED        STATUS        PORTS                NAMES
2fa2b602ba25   nginx:mainline-alpine   "/docker-entrypoint.…"   10 hours ago   Up 10 hours   0.0.0.0:80->80/tcp   docker_config_nginx_recipes_1
68583642b6bb   vabene1111/recipes      "/opt/recipes/boot.sh"   10 hours ago   Up 10 hours   8080/tcp             docker_config_web_recipes_1
1f98fda8b865   postgres:11-alpine      "docker-entrypoint.s…"   10 hours ago   Up 10 hours   5432/tcp             docker_config_db_recipes_1

tandoor@linux14:~$ docker exec -it 68583642b6bb echo "test"
test
tandoor@linux14:~$ docker exec -it 68583642b6bb ping dc1.mydomainname.org
PING dc1.mydomainname.org (mySubNet.2): 56 data bytes
64 bytes from mySubNet.2: seq=0 ttl=127 time=0.936 ms
64 bytes from mySubNet.2: seq=1 ttl=127 time=0.604 ms
64 bytes from mySubNet.2: seq=2 ttl=127 time=0.486 ms
^C
--- dc1.mydomainname.org ping statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 0.486/0.675/0.936 ms
tandoor@linux14:~$
```

As always, domain and subnets disguised.

If that's of any relevance, this is the docker-compose file I used to create the setup:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media

volumes:
  nginx_config:
  staticfiles:
```
But I wouldn't see any problem here. With the initially created admin account I am able to use Tandoor as expected.
