### DISCUSSION TITLE
Trying to move Tandoor to a standalone PG server to consolate db's to one instance.

### DISCUSSION THREAD

**Discussion by bonelifer** [TandoorRecipes/recipes#1992] [Q&A] [answered]
Never connects to new PG instance. I am able to connect with Adminer. Using the same info as in the .env file to setup the new user/db. Adminer 4.8.1 reports PG 14.4. I adjusted the .env file to "POSTGRES_HOST=172.80.9.3" to match my PG db's ip.

```
version: '3.3'
services:
    basic-postgres:
        environment:
            - basic-postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=PASSWORD
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - '/media/william/DataOrig/homelab/postgres/data/:/var/lib/postgresql/data'
        ports:
            - '5432:5432'
        image: postgres:latest

    adminer:
        image: adminer
        restart: always
        ports:
            - 8787:8080
```

Setup of user/database in Adminer:
```
CREATE ROLE tandoor;
CREATE USER tandoor WITH PASSWORD 'PASSWORD';
GRANT tandoor TO tandoor;
ALTER ROLE tandoor WITH LOGIN;
CREATE DATABASE tandoor;
GRANT ALL PRIVILEGES ON DATABASE tandoor to tandoor;
GRANT CONNECT ON DATABASE tandoor TO tandoor;
GRANT USAGE ON SCHEMA public TO tandoor;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tandoor;
ALTER USER tandoor WITH NOSUPERUSER;
REVOKE connect ON DATABASE tandoor FROM PUBLIC;
ALTER ROLE tandoor SET timezone TO 'UTC';
ALTER ROLE tandoor SET client_encoding TO 'utf8';
ALTER ROLE tandoor SET default_transaction_isolation TO 'read committed';
ALTER DATABASE tandoor OWNER TO tandoor;
commit;
```

Adminer output when importing:

```
--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: tandoor
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin

Error in query (4): Unknown error. 

474 queries executed OK. (2.086 s)
```

PORTAINER LOGS

```
Checking configuration...
Waiting for database to be ready...

Database not reachable. Maximum attempts exceeded.
Please check logs above - misconfiguration is very likely.
Make sure the DB container is up and POSTGRES_HOST is set properly.
Shutting down container.
Checking configuration...
Waiting for database to be ready...

Database not reachable. Maximum attempts exceeded.
Please check logs above - misconfiguration is very likely.
Make sure the DB container is up and POSTGRES_HOST is set properly.
Shutting down container.
Checking configuration...
Waiting for database to be ready...

Database not reachable. Maximum attempts exceeded.
Please check logs above - misconfiguration is very likely.
Make sure the DB container is up and POSTGRES_HOST is set properly.
Shutting down container.
Checking configuration...
Waiting for database to be ready...
Checking configuration...
Waiting for database to be ready...
```
