### DISCUSSION TITLE
How to change from Port 80 to a diffrent one?

### DISCUSSION THREAD

**Discussion by kl4ppdrachen** [TandoorRecipes/recipes#2634] [Q&A]
Hello chefs from around the world,

I want to change the Port 80 from nginx to 5001. But I don't know what to put into my nginx.conf and running every time into trouble with nginx. I also use traefik for the connection from outside. Atm I'm using `gunicorn=1` with traefik labels on tandoor. 

My docker-compose.yaml looks like this:
```yaml
version: '3'
services:
  postgresql:
    container_name: tandoor_db
    restart: always
    image: postgres:11-alpine
    volumes:
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - tandoor-net
  tandoor:
    container_name: tandoor
    restart: always
    image: vabene1111/recipes
    ports:
      - 5000:8080
    volumes:
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/static:/opt/recipes/staticfiles
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/files:/opt/recipes/mediafiles
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/nginx:/opt/recipes/nginx/conf.d
    env_file:
      - ./.env
    depends_on:
      - postgresql
    networks:
      - tandoor-net
      - traefik-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.tandoor.rule=Host(`kochbuch.mnhrdt.de`)
      - traefik.http.routers.tandoor.tls=true
      - traefik.http.routers.tandoor.tls.certresolver=le
      - traefik.port=5000      
  nginx:
    container_name: tandoor_rp
    restart: always
    image: nginx:mainline-alpine
    volumes:
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/nginx:/etc/nginx/conf.d:ro
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/static:/static:ro
      - /srv/dev-disk-by-uuid-xxx/server/tandoor/files:/media:ro
    env_file:
      - ./.env
    depends_on:
      - tandoor
    networks:
      - tandoor-net


networks:
  tandoor-net:
  traefik-net:
      external: true
```

Greetings!
