### DISCUSSION TITLE
Display Tandoor today's meal in Lovelace - Home Assistant

### DISCUSSION THREAD

**Discussion by blowk** [TandoorRecipes/recipes#2671] [Show and tell]
How to display today's meal in HA.

1. Get Tandoor API Key

Well, first you need go to /settings page to get API key. Create a new one that only 'read'.
Ex. tda_************_******_***********fd58

2. Create your HA sensors
Create a REST sensor with today's meal plan. It's only fetch the first item.
```
  - platform: rest
    resource_template: http://tandoor:9928/api/meal-plan/?from_date={{ now().strftime('%Y-%m-%d') }}&to_date={{ now().strftime('%Y-%m-%d') }}
    name: Tandoor todays meal
    headers:
      Authorization: Bearer <<API_TOKEN>>
      Content-Type: application/json
    value_template: "{{ value_json[0].recipe_name }}"
    json_attributes_path: "$.[0].recipe"
    json_attributes: 
     - id
     - name
     - image
    force_update: true
    scan_interval: 300
```

4. Create General Camera Entity
Create a general camera. 
In Home Assistant, go to Integrations and create a new generic camera.
In the input field, you can use
`{{ states.sensor.tandoor_todays_meal.attributes.image }}`

Rename the new camera to entity tandoor_todays_meal_image

5. Create a Lovelace card
Now you can place you card on your dashboard.
```
show_state: true
show_name: true
camera_view: auto
type: picture-entity
entity: sensor.tandoor_todays_meal
name: 'Today: '
camera_image: camera.tandoor_todays_meal_image
card_mod:
  style: |
    ha-card {
    max-height: 300px !important;
    overflow: hidden;
    display: flex;
    align-items: center;
    justify-content: center;
    }
```

If you have any suggestions, improvements or you made your own custome lovelace card, let me know.

**Comment by pbathuk** [comment]
Just wanted to say thank you for this - great help.
FYI I had a lot of errors / issues.. as it turns out you can't have (as I was):
`Authorization: Bearer !secret tandoor_api`
Not sure why not.. as thought it would auto resolve like:

`api_key: !secret cloudflare_api` for example...
Maybe I need to do : `Authorization: !secret tandoor_api` with the `Bearer` in the secrets file as well...

**Reply by blowk** [reply]
My pleasure and thank you for your information.

I'm still learning and I managed to load the recipes from specific day into Home Assistant. I wrote python script (used pyscript add-on) that loads the recipes and make a sensor for each recipe.
Then I could make a card with this info for example to cast to Google Home Hub or other device.

I haven't found another way to display the website to Google Home Hub because the instance isn't expose over HTTPS.

**Comment by nicknickalive** [comment]
I got this working, thank you! QQ, does it just show one meal or all of them? I am only seeing the first one show up

**Reply by blowk** [reply]
Yes, that's true. It only fetch the first meal.
I will post my new implementation with pyscript here.

**Comment by blowk** [comment]
Here is my other implementation with pyscript. Still experimental
Created two files "fetch_mealplan.py" and "update_recipe_card.py"

**fetch_mealplan.py**
Change <<API_TOKEN>> to your API key ex. tda_******__***********fd58

`@service
def fetch_mealplan():
    
    import requests
    import json
    from datetime import datetime
    import asyncio
    
    # Delete previous sensors
    recipe_meals_state = 0
    
    try:
        recipe_meals_state = state.get("sensor.recipe_all_meals")
        if recipe_meals_state is None:
            recipe_meals_state = 0
        else:
            recipe_meals_state = int(recipe_meals_state)
    except:
        recipe_meals_state = 0
    
    if recipe_meals_state:
            for i in range(1, recipe_meals_state):
                sensor_del = f"sensor.recipe_meals_{i}"
                if(state.get(sensor_del)):
                    state.delete(sensor_del)
        
    await asyncio.sleep(10)
    
    url = f"http://tandoor:9928/api/meal-plan/?from_date={datetime.now().strftime('%Y-%m-%d')}&to_date={datetime.now().strftime('%Y-%m-%d')}"


    headers = {
        "Authorization": "Bearer <<API_TOKEN>>,
        "Content-Type": "application/json"
    }
    
    response = task.executor(requests.get, url, headers = headers)
    
    if response.status_code == 200:
        recipe_data = response.json()
        
        num_recipes = recipe_data['count']
        state.set("sensor.recipe_all_meals", num_recipes, attributes={"unique_id": 'recipe_all_meals'})
        
        recipes = recipe_data['results']
        
        # Create new sensors with recipe data
        recipes_list = []
        for index, recipe in enumerate(recipes):
            sensor_id = f"sensor.recipe_meals_{index + 1}"
            recipe_info = {
                "unique_id": sensor_id,
                "id": recipe['recipe']['id'],
                "name": recipe['recipe']['name'],
                "image": recipe['recipe']['image'],
                "description": recipe['recipe']['description'],
                "servings": recipe['servings']
            }
            
            recipes_list.append(recipe_info)
            
            # Save alle data on new sensor
            state.set(sensor_id, index, attributes=recipe_info)
       
        sensor.recipe_all_meals.recipes = recipes_list
        
    else:
        sensor.recipe_all_meals = '0'
`

**update_recipe_card.py**

`@service
def update_recipe_card(recipe_id, servings=None):
    # servings
    import requests
    
    if recipe_id:
   
        url = f"http://tandoor:9928/api/recipe/{recipe_id}/"
        headers = {
            "Authorization": "Bearer <<API_TOKEN>>",
            "Content-Type": "application/json"
        }
        
        response = task.executor(requests.get, url, headers = headers)

        if response.status_code == 200:
            scaling_factor = 1
            sensor.recipe_details = recipe_id
            recipe_data = response.json()
            recipe_name = recipe_data.get('name', '')
            recipe_image = recipe_data.get('image', '')
            recipe_description = recipe_data.get('description', '')
            recipe_steps = recipe_data.get('steps')
            recipe_servings = recipe_data.get('servings')
            
            if servings:
                scaling_factor = (servings / recipe_servings)
            
            ingredient_list = []
            steps_list = []
            
            if recipe_steps:
                for step in recipe_steps:
                    
                    stepinstruction = step['instruction']
                    newstepinstruction = stepinstruction.replace("\n", "<br>")
                    steps_list.append(newstepinstruction)
                    
                    for ingredient in step['ingredients']:
                        amount = '.'
                        unit = '.'
                        foodname = '.'
            
                        if 'amount' in ingredient:
                            amount = (ingredient['amount'] * scaling_factor)
                        if 'unit' in ingredient and ingredient['unit'] is not None and 'name' in ingredient['unit']:
                            unit = ingredient['unit']['name']
                        if 'food' in ingredient and 'name' in ingredient['food']:
                            foodname = ingredient['food']['name']
                        ingredient_str = f"{amount} {unit} {foodname}"

                        if 'note' in ingredient:
                            if ingredient['note']:
                                ingredient_str += f" ({ingredient['note']})"
                                
                        if amount > 0:
                          ingredient_list.append(ingredient_str)
            
            sensor.recipe_details.name = recipe_name
            sensor.recipe_details.description = recipe_description
            sensor.recipe_details.servings = servings
            sensor.recipe_details.image = recipe_image
            sensor.recipe_details.ingredients = ingredient_list
            sensor.recipe_details.steps = steps_list
            
        else:
            sensor.recipe_details = 'Error'
`

Now in your HA dashboard you can create a button to fetch all data from Tandoor.
Call script: pyscript.fetch_mealplan

For example you can show then all meals in a row

```
  - type: custom:auto-entities
    card:
      type: grid
      columns: 1
      square: false
    card_param: cards
    filter:
      include:
        - entity_id: sensor.recipe_meals_*
          options:
            type: custom:button-card
            icon: mdi:silverware-fork-knife
            name: |
              [[[ return entity.attributes.attributes.name; ]]]
            entity: this.entity_id
            show_label: false
            show_state: false
            custom_fields:
              arrow: |
                [[[
                  return `<ha-icon
                    icon="mdi:chevron-right"
                    style="width:16px; height: 16px;">
                    </ha-icon>`
                ]]]  
            tap_action:
              action: javascript
              javascript: |
                [[[
                  hass.callService(
                    "pyscript",
                    "update_recipe_card",
                    { recipe_id: entity.attributes.attributes.id, servings: entity.attributes.attributes.servings}
                  );

                 window.history.pushState(null,"","/dashboard/recipes");
                 window.dispatchEvent(new CustomEvent("location-changed"));
                 ]]]
            styles:
              grid:
                - grid-template-areas: "\"i n arrow\" \"i s arrow\""
                - grid-template-columns: 60px 1fr 40px
              icon:
                - width: 24px
                - color: black
              img_cell:
                - background: "#C1D8C3"
                - border-radius: 515px
                - width: 50px
                - height: 50px
              name:
                - justify-self: start
                - font-size: 20px
                - font-weight: 500
                - padding-left: 10px
              card:
                - margin: 0
                - border-radius: 50px
                - padding: 12px 14px 12px 8px
              state:
                - justify-self: start
                - font-size: 14px
                - color: black
                - opacity: "0.7"
                - padding-left: 10px
              custom_fields:
                arrow:
                  - justify-self: end
                  - font-size: 14px
                  - color: black
                  - opacity: "0.7"
```

In a second view called _/dashboard/recipes_ you can then load all info from _sensor.recipe_details_
