### DISCUSSION TITLE
Type error on system page

### DISCUSSION THREAD

**Discussion by timkolloch** [TandoorRecipes/recipes#3072] [Q&A] [answered]
Good evening,

I have a problem with the system settings.

# Problem

When I try to navigate to the System page from my profile I get following error:

 ## TypeError at /system
  <pre class="exception_value">'&gt;=' not supported between instances of 'tuple' and 'int'</pre>
  
Request Method: | GET
-- | --
http://192.168.178.8:8082/system/
4.2.11
TypeError
'>=' not supported between instances of 'tuple' and 'int'
/opt/recipes/cookbook/views/views.py, line 300, in system
cookbook.views.views.system
/opt/recipes/venv/bin/python
3.12.2
['/opt/recipes',  '/opt/recipes/venv/bin',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/opt/recipes/venv/lib/python3.12/site-packages']
Thu, 28 Mar 2024 20:33:43 +0100

# Code
Here is my docker-compose:

````
docker-compose.yml                                        
version: "3.4"
services:
  db:
    restart: unless-stopped
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./docker-compose.env
  web:
    restart: always
    image: vabene1111/recipes:latest
    env_file:
      - ./docker-compose.env
    ports:
      - "8082:8080"
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db
````

# Final question

Is this a general implementation problem or what could I've done wrong?

If you need anything else let me know and thank you in advance for any help!

Best wishes,

Tim
