### ISSUE TITLE
Can't get rid of mixed active content / same site issues

### ISSUE THREAD

**Issue by tooManyArguments** [TandoorRecipes/recipes#1080]
I am using Nginx Proxy Manager as a front for Tandoor. And no matter which setting i try i still get mixed content issues when using it from the internet (because content is served from http on localhost to NPM which is https)
Is there a way to use for example `X_FRAME_OPTIONS="sameorigin"` in the .env file to get rid of this? Anyone knows a solution?

here is the .env:
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0
SQL_DEBUG=0
# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*
SECRET_KEY=xxxxx
# your default timezone See https://timezonedb.com/time-zones for a list of timezones
TIMEZONE=Europe/Stockholm
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=xxxxx
POSTGRES_PASSWORD=xxxxx
POSTGRES_DB=xxxxx
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
X_FRAME_OPTIONS="sameorigin"


```

and here is the docker-compose.yml

```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 634:80
      - 635:443
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static
      - ./mediafiles:/media
    environment:
      - http.host=0.0.0.0
      - http.port=80
      - "http.cors.allow-origin=http://localhost"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
networks:
  default:
    external:
      name: scoobydoo

volumes:
  nginx_config:
  staticfiles:

```

And finally, here is the NPM docker-compiose.yml

```
version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - X_FRAME_OPTIONS="sameorigin"
      - http.host=0.0.0.0
      - http.port=80
      - "http.cors.allow-origin=http://mat.blotare.club"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
networks:
  default:
    external:
      name: scoobydo
```

As anyone can probaly see, this is a mix and match from different solutions from different sites, and i have had no luck yet.
