### ISSUE TITLE
Import Issues in firefox

### ISSUE THREAD

**Issue by venohm69** [TandoorRecipes/recipes#1083]
## Issue
Please describe your problem here
No nothing displayed for recipes after import.

## Setup Info
Version: (can be found on the system page since v0.8.4)
tandoor 1.0.1
Debian 11

Other relevant information regarding your problem (proxies, firewalls, etc.)
Using apache as reverse proxy.

### `.env`
Please include your `.env` config file (**make sure to remove/replace all secrets**)
```
env content
```

### `docker-compose.yml`
When running with docker compose please provide your `docker-compose.yml`
```
docker-compose.yml content
```

### Logs
If you feel like there is anything interesting please post the output of `docker-compose logs` at
container startup and when the issue happens.

export file emailed.

**Comment by vabene1111** [comment]
sorry i havn't gotten around to your mail yet, hope to get that done in the next few days but pretty busy right now.

**Comment by smilerz** [comment]
@venohm69 a couple of questions:
a) are there any errors in the browser console?
b) when you go to recipes under the API Browser (top right menu) are there recipes listed there?
c) if the answer to B is 'NO' are there recipes listed in the Admin page (also top right)?

**Comment by venohm69** [comment]
One more point of reference.  I tried extracting one of the recipies from the export.zip and import a single recipe. 1.zip.  I got an error that said the file was not a zip file.

During the import of the full file, it lists each recipe by name and says imported.  I see no errors.  I wiped the database to try a single file import but can import the full export again since I have a blank database again if needed.

**Comment by smilerz** [comment]
1 or all shouldn't matter - just trying to identify where the issue lies.

**Comment by venohm69** [comment]
Well, I did get the error trying to import the single file 1.zip that I extracted from the full export.zip.  I can open the file in xarchiver and it shows t he recipe.json and the image.jpeg but tandoor will not import the file 1.zip.

**Comment by vabene1111** [comment]
ok so i just imported your file on my local test system and everything seems to work correctly. I also imported some of the recipes into the hosted version of tandoo which has the default docker setup and that worked as well.

Now the question is whats wrong with the setup that you cannot import the recipes. Can you, just to see if this might actually be a frontend issue, go to the admin page and select recipes and see if the recipes are listed there/if they contain any information ?

Could you also share logs, configuration files and so on so that i can get a picture of whats going on here ?

**Comment by venohm69** [comment]
Okay, So it may be something that Apache is blocking.  I'll take a look at my logs there as well...  I've started a new install and started from scratch, but I'll set up a test VM and test it there to see if I can find more..  It would be a lot quicker if I could just import them.  If I get it working in the test VM, then I'll just drop the database on my actual host and try again.

**Comment by vabene1111** [comment]
one thing please also look at your browser console to see if you are getting mixed content/request warnings/errors there

**Comment by MaxJa4** [comment]
I actually had this issue too while migrating to my new server provider. I copied the static and media files and any other persistent data and started the container again. 
Also no recipes shown, but recognized by the backend.
Sadly I don't know how I fixed it... I hope I can remember soon though 😅

**Comment by venohm69** [comment]
Okay, it seems Firefox was the issue.  I went to test again to provide more data but after the discussion I decided to try Chromium.  The recipes imported fine.  I have one that imported blank, but that is easy to fix as opposed to redoing all of them.  I still will open up the JSON file and get the imported from link and just reimport that one recipe.

Sorry for the trouble and thanks once again for everyone's assistance on this.  It would have never occurred to me that Firefox was the issue without someone else testing and showing that the export file worked.  I may have to dump the LTS version of firefox and try the newer versions to see if they work.

**Comment by vabene1111** [comment]
I personally dislike firefox for always breaking things or not supporting current standards but i really dont know how they could screw up the import feature :joy: i will definitely also give this a try to see if i can reproduce your issue with a current version and if so how it could possible be fixed.

**Comment by jamolnng** [comment]
For what it's worth, I had an issue that sounds very similar and it was because I had my nginx Recipes.conf set up wrong. The recipes would import and show up in the backend but I was getting "403 forbidden: authentication credentials were not provided" errors when loading parts of the main page so it appeared normal except no recipes. I did not try it in any browser other than Firefox before I got my setup working. If this helps anyone here is my docker-compose.yml, Recipes.conf, and .env files

docker-compose.yml
```yaml
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx:/opt/recipes/nginx/conf.d
      - mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 6680:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - mediafiles:/media:ro

volumes:
  nginx:
  staticfiles:
  postgresql:
  mediafiles:
```

Recipes.conf
```Nginx
server {
  listen 80;
  server_name recipes.domain.tld;

  # client_max_body_size 128M;

  # serve media files
  location /media/ {
    alias /media/;
  }
  # pass requests for dynamic content to gunicorn
  location / {
    proxy_set_header Host $http_host; # try $host instead if this doesn't work
    # proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://web_recipes:8080; # replace port
    proxy_redirect http://web_recipes:8080 https://recipes.domain.tld; # replace port and domain
    
    error_page 502 /errors/http502.html;
  }

  location /errors/ {
    alias /etc/nginx/conf.d/errorpages/;
    internal;
  }
}
```

.env
```bash
DEBUG=0
SQL_DEBUG=0
TANDOOR_PORT=8080
ALLOWED_HOSTS=recipes.domain.tld
SECRET_KEY=
TIMEZONE=America/Chicago
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
ENABLE_SIGNUP=0
```
