### ISSUE TITLE
Run processes inside container as non-root user

### ISSUE THREAD

**Issue by graduatio** [TandoorRecipes/recipes#1257]
**Is your feature request related to a problem? Please describe.**
The processes inside the recipes container currently run as user root. This is potentially problematic for security reasons.

**Describe the solution you'd like**
Whenever possible the processes should run as non-root user.

**Comment by graduatio** [comment]
I tried to run all containers (nginx, postgres and recipes) as a non-root user. The nginx and postgres docker documentations describe how the containers can run as an arbitrary non-privileged user. I followed the steps below:

For the nginx container:

- added `user: "${UID}:${GID}"` in `docker-compose.yaml` to the `nginx_recipes` section
- added to the `volumes` section in `docker-compose.yaml`:
	`- ./nginx.conf:/etc/nginx/nginx.conf`
- created a `nginx.conf` file in the current directory with following redefined directives:
```
pid        /tmp/nginx.pid;
http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp_path;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
}
```
For the postgres container:
- changed to a Debian Variant image (e.g. postgres:latest)
- added `user: "${UID}:${GID}"` in `docker-compose.yaml` to the `db_recipes` section

For the recipe container:
- added `user: "${UID}:${GID}"` in `docker-compose.yaml` to the `web_recipes` section

Before I started the containers:
- added `UID=` and `GID=` with the desired values to the `.env` file
- created a `mediafiles` and a `postgresql` directory and used `chown` to change ownership to the user which should run the containers

With this setup the database and the nginx server seem to work properly. Tandoor can be accessed by opening the ip-address. But the docker-compose logs show permission errors of the recipes container which cannot change files in `/opt/recipes` when executing the commands in `boot.sh`.
This error occures because `opt/recipes` was created by user root. Changing the owner of the files inside the container manually resolves the problem temporarily.
Maybe this issue can be resolved by setting a default user and changing the owner of `opt/recipes` in the Dockerfile.

**Comment by vabene1111** [comment]
thanks, i will take a look at this at some point when the more pressing features are taken care of

**Comment by Akruidenberg** [comment]
Any progress so far. I would like to run the recipe container rootless. The trick of @graduatio is working, only manually .

**Comment by graduatio** [comment]
@Akruidenberg unfortunately the processes in the default container still run as user root. To simplify the modification process of the recipe container to run as a non-root user I currently use following docker-compose.yaml in combination with an additional Dockerfile in `./recipes`:


**docker-compose.yaml**
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    build: ./recipes/
    user: "${UID}:${GID}"
    restart: always
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:
```


**Dockerfile**
```
FROM vabene1111/recipes:latest
RUN adduser -D --uid 999 tandoor
RUN chown -R 999:999 /opt/recipes
USER 999:999
ENTRYPOINT ["/opt/recipes/boot.sh"]
```

The`UID` and `GID` have to be specified in the `.env` file and should match the values in the Dockerfile.
