### ISSUE TITLE
Wrong link of Tandoor brand logo in navigation bar

### ISSUE THREAD

**Issue by mrcblt** [TandoorRecipes/recipes#1470]
### Tandoor Version

1.0.5.2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Host nginx

### Bug description

The link to which the Tandoor logo in the navigation bar points seems to be the internal address of the Gunicorn server, in my case `0.0.0.0:8080`. In my opinion, the logo should point to the index URL of the page, e.g. `https://mydomain.org`.

I already tested a possible fix and will submit a pull request soon.

**Comment by mrcblt** [comment]
Thank you, the headers were indeed not there. After adding them to my nginx configuration, I could see them on the `/system/` page. Unfortunately, I now get a 403 response with the message "CSRF verification failed. Request aborted" for any POST request like saving any preferences.

My nginx configuration looks like this (sensitive information is shown as `...`):
```
server {
    listen 44444 ssl http2;
    server_name ...;

    ssl_certificate ...;
    ssl_certificate_key ...;
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

    client_max_body_size 128M;

    location /media/ {
        alias /media/;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://127.0.0.1:8123;
    }
}
```

My docker-compose.yml looks like this:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    ports:
      - 127.0.0.1:8123:8080
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
```

Do you have any idea why this happens?

Additionally, the "X-Forwarded-Port" header seems to be ignored, as the Tandoor logo in the navigation bar now correctly points to the right domain, but without the custom port.
