### ISSUE TITLE
Add documentation for Nginx Proxy Manager

### ISSUE THREAD

**Issue by speendo** [TandoorRecipes/recipes#1518]
### Documentation link

https://docs.tandoor.dev/install/docker/#reverse-proxy

### Affected section

Installation

### Issue description

It would be great to have a short section on how to install with Nginx Proxy Manager. Most information should already be available in this issue: https://github.com/TandoorRecipes/recipes/issues/452

Thank you for this great product!

**Comment by Rgamer84** [comment]
I beat my head against a wall for a little bit on this.  Hopefully this helps someone!

NGINX Proxy Manager Docker Compose:
```
version: "3.9"
services:
 nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /docker/npm/data:/data
      - /docker/npm/letsencrypt:/etc/letsencrypt
      - /docker/tandoor/mediafiles:/media
```
I have my docker files for NGINX Proxy Manager under /docker/npm/.  Note that I exposed an additional volume to my tandoor media files folder.  I store my media files under /docker/tandoor/mediafiles/ and have it mapped to /media within the nginx proxy manager container.  Modify this to meet your environment.

From there you should be able to add your Proxy Host into Nginx Proxy Manager as normal however under advanced you should place in the following under Custom Nginx Configuration:
```
# serve media files
   location /media {
   alias /media/;
   }
```

Your images should now load!  I didn't include the rest of my docker compose script as you should be able to follow the other general installation examples already written in the existing documentation.
