### ISSUE TITLE
app doesn't start after update

### ISSUE THREAD

**Issue by HerrFrutti** [TandoorRecipes/recipes#1652]
Docker logs show:

```
Nginx configuration file could not be found at the default location!
Path: /opt/recipes/nginx/conf.d/Recipes.conf
Waiting for database to be ready...
```

compose:

```
version: "3"
services:
  db_recipes:
    restart: always
    container_name: tandoor_db
    image: postgres:11-alpine
    user: 1000:1000
    volumes:
      - ./postgresql:/var/lib/postgresql/data:z
    env_file:
      - ./.env
    networks:
      - private

  web_recipes:
    image: vabene1111/recipes:1.1.3
    restart: always
    container_name: tandoor_app
    user: 1000:1000
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles:z
      - ./nginx_config:/opt/recipes/nginx/conf.d:z
      - ./mediafiles:/opt/recipes/mediafiles:z
    depends_on:
      - db_recipes
    networks:
      - private

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    container_name: tandoor_nginx
#    ports:
#      - 9900:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - ./staticfiles:/static:z
      - ./mediafiles:/media:z
    networks:
      - private
      - reverseproxy-nw
      - overnet

networks:
  private:
  reverseproxy-nw:
    external: true
  overnet:
    external: true

```

login into the container via shell, I can find the Recipes.conf... I don't know what's the problem. I've allready tested version 1.1.3 and latest (1.1.4). Error remains. Earlier today I used tandoor just fine. After the update to latest (1.1.4) it briked...

Thanks for the help :)
