### ISSUE TITLE
Problem with docker-compose

### ISSUE THREAD

**Issue by nicobauernodered** [TandoorRecipes/recipes#2159]
### Tandoor Version

1.4.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

I fetched the docker-compose via wget from the address you provided. 
Now when I want to run Docker-compose up -d I got the message that no image was started. D
I was able to fix that by moving the image specification to a new line and then putting a - in front of it.

After that the following message was displayed when starting the service.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.db_recipes.image contains an invalid type, it should be a string
services.web_recipes.image contains an invalid type, it should be a string

**Comment by gloriousDan** [comment]
I just tested it and for me with docker-compose version 2.12.2 I experienced none of the issues.

Which docker-compose.yml file did you use and what's your docker-compose version?
Get it with `docker-compose version`

**Comment by nicobauernodered** [comment]
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

and Reverse Proxy with this Link to the docker-compose
wget https://raw.githubusercontent.com/vabene1111/recipes/develop/docs/install/docker/traefik-nginx/docker-compose.yml
and this env file
wget https://raw.githubusercontent.com/vabene1111/recipes/develop/.env.template -O .env

**Comment by gloriousDan** [comment]
It seems to me like the problem might be the older version of docker-compose which you have installed.

Try installing an up to date version (choose one of the ways here: https://docs.docker.com/compose/install/).

**Comment by nicobauernodered** [comment]
I have install an newer version and i get the same error.
Docker Compose version v2.12.2

services.db_recipes.image must be a string

**Comment by frudolph77** [comment]
I've setup Tandoor using the provided `docker-compose.yml` and `.env`  by my own, just yesterday. The only problem I've had was the broken port settings, set by this commit https://github.com/TandoorRecipes/recipes/commit/37bd2017b01458b01bda29c7b919d36c931d47e3

Ok, I'm not using traefik, but maybe my docker-compose helps anyway

```yaml
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - nginx_config:/opt/recipes/nginx/conf.d
      - staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8099:80
    env_file:
      - ./.env
    depends_on:
      - web_recipes
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:

```
