### ISSUE TITLE
Bad Request 400 running behind traefik

### ISSUE THREAD

**Issue by mrpew** [TandoorRecipes/recipes#2279]
### Issue

I get a 400: Bad Request blank page when trying to access my (fresh) instance at `https://recipes.domain.tld`.

Forwarding port 8080 of the container `recipes-web` to my local machine and accessing via `localhost:8080`  yields the same result.

Note: authelia is set to bypass for this route for now.

### Tandoor Version

latest docker, 0ba3d75eb4704683f777ff3ad989c8b67e2b0731316fd5a316754c6779cab863

### OS Version

Ubuntu Server 22.04

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Environment file

```shell
DEBUG=1

ALLOWED_HOSTS=recipes.domain.tld

SECRET_KEY=[...]

TIMEZONE=Europe/Berlin

DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=recipes-db
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=[...]
POSTGRES_DB=djangodb

FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

STATIC_URL=/static/
MEDIA_URL=/media/
GUNICORN_MEDIA=0

REVERSE_PROXY_AUTH=0
```

### Docker-Compose file
**recipes.yml**

```shell


version: "2.1"
services:
  recipes-db:
    container_name: recipes-db
    restart: unless-stopped
    image: postgres:11-alpine
    volumes:
      - ${DATA_ROOT}/recipes/postgresql:/var/lib/postgresql/data
    env_file:
      - ./recipes.env
    networks:
      - recipes-default

  recipes-web:
    hostname: web_recipes
    container_name: recipes-web
    image: vabene1111/recipes
    restart: unless-stopped
    env_file:
      - ./recipes.env
    volumes:
      - ./nginx.conf.d:/opt/recipes/nginx/conf.d:ro
      - ${DATA_ROOT}/recipes/recipes_staticfiles:/opt/recipes/staticfiles
      - ${DATA_ROOT}/recipes/mediafiles:/opt/recipes/mediafiles
    networks:
      - recipes-default
    #depends_on:
    #  - recipes-db

  recipes-nginx:
    container_name: recipes-nginx
    image: nginx:mainline-alpine
    restart: unless-stopped
    env_file:
      - ./recipes.env
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d:ro
      - ${DATA_ROOT}/recipes/recipes_staticfiles:/static:ro
      - ${DATA_ROOT}/recipes/mediafiles:/media:ro
    networks:
      - proxy-tier
      - recipes-default
```
**docker-compose.yml**
```
services:
  # ===========================================================================
  # Recipes
  recipes-nginx:
    extends:
      file: ./recipes/recipes.yml
      service: recipes-nginx
    depends_on:
      - recipes-web
    labels:
      # TRAEFIK ROUTER LABELS / recipes : <port discovery>
      - "traefik.enable=true"
      - "traefik.http.routers.proxy-recipes.rule=Host(`recipes.domain.tld`)"
      - "traefik.http.routers.proxy-recipes.entrypoints=websecure"
      - "traefik.http.routers.proxy-recipes.tls.certresolver=proxyresolver"
      - "traefik.http.routers.proxy-recipes.tls.domains[0].main=recipes.domain.tld"
      - "traefik.http.routers.proxy-recipes.tls.options=default"
      - "traefik.http.middlewares.headers-recipes.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.headers-recipes.headers.sslredirect=true"
      - "traefik.http.middlewares.headers-recipes.headers.browserXssFilter=true"
      - "traefik.http.middlewares.headers-recipes.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.headers-recipes.headers.accesscontrolalloworiginlist=https://*.domain.tld"
      - "traefik.http.middlewares.headers-recipes.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.headers-recipes.headers.addvaryheader=true"
      - "traefik.http.routers.proxy-recipes.middlewares=authelia@docker,headers-recipes"
      - "traefik.http.services.serv-recipes.loadbalancer.server.port=80"
  
  recipes-web:
    extends:
      file: ./recipes/recipes.yml
      service: recipes-web
    depends_on:
      - recipes-db

  recipes-db:
    extends:
      file: ./recipes/recipes.yml
      service: recipes-db
```

### Relevant logs

**recipes-nginx**
```shell

172.18.0.5 - - [21/Jan/2023:10:38:49 +0000] "GET / HTTP/1.1" 400 154 "https://auth.domain.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "[...]"
172.18.0.5 - - [21/Jan/2023:10:38:49 +0000] "GET /favicon.ico HTTP/1.1" 400 154 "https://recipes.domain.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" "[...]"
```

**recipes-web**
```
172.23.0.4 - - [21/Jan/2023:11:40:31 +0100] "GET / HTTP/1.0" 400 143 "https://auth.domain.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.23.0.4 - - [21/Jan/2023:11:40:31 +0100] "GET /favicon.ico HTTP/1.0" 400 143 "https://recipes.domain.tld/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```
