### ISSUE TITLE
Images not showing - 404 error with traefik

### ISSUE THREAD

**Issue by kvnklk** [TandoorRecipes/recipes#2497]
### Tandoor Version

1.4.12

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When trying to add an image to a recipe it's not showing up, I see 404 error in the browser console:

`https://recipes.domain.com/media/recipes/XXXXXXXXXXXXXXXXX.jpg 404`.

Here is my current `docker-compose.yml`:

```
version: "3.9"

# SERVICES
services:

  tandoor_db:
    restart: always
    container_name: tandoor_db
    image: postgres:14-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file: .env
    networks:
      default: null

  tandoor_web:
    restart: always
    container_name: tandoor_web
    image: vabene1111/recipes
    env_file: .env
    networks:
      default: null
      proxy: null
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./data/mediafiles:/opt/recipes/mediafiles
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.tandoor-secure.entrypoints: websecure
      traefik.http.routers.tandoor-secure.middlewares: default@file
      traefik.http.routers.tandoor-secure.rule: Host(`recipes.domain.com`)
      traefik.http.routers.tandoor-secure.service: tandoor
      traefik.http.routers.tandoor-secure.tls: "true"
      traefik.http.routers.tandoor-secure.tls.certresolver: http_resolver
      traefik.http.routers.tandoor.entrypoints: web
      traefik.http.routers.tandoor.rule: Host(`recipes.domain.com`)
      traefik.http.services.tandoor.loadbalancer.server.port: "8080"
    depends_on:
      - tandoor_db


### NETWORKS
networks:
  default:
  proxy:
    external: true

volumes:
  nginx_config:
  staticfiles:
```

And here is my `.env` file:

```
DEBUG=0
SQL_DEBUG=0
DEBUG_TOOLBAR=0
ALLOWED_HOSTS=*
SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXX
TIMEZONE=Europe/Berlin
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=tandoor_db
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=XXXXXXXXXXXXXXXXX
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
```

Everything else works fine except for the images.

### Relevant logs

```shell
tandoor_db   | 2023-06-08T20:45:24.222033426Z 2023-06-08 20:45:24.221 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
tandoor_db   | 2023-06-08T20:45:24.222056350Z 2023-06-08 20:45:24.221 UTC [1] LOG:  listening on IPv6 address "::", port 5432
tandoor_db   | 2023-06-08T20:45:24.223754326Z 2023-06-08 20:45:24.223 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
tandoor_db   | 2023-06-08T20:45:24.227160969Z 2023-06-08 20:45:24.227 UTC [21] LOG:  database system was shut down at 2023-06-08 20:42:39 UTC
tandoor_db   | 2023-06-08T20:45:24.233426019Z 2023-06-08 20:45:24.232 UTC [1] LOG:  database system is ready to accept connections
tandoor_web  | 2023-06-08T20:45:24.427533777Z Checking configuration...
tandoor_web  | 2023-06-08T20:45:24.427657464Z Waiting for database to be ready...
tandoor_web  | 2023-06-08T20:45:24.432559494Z Database is ready
tandoor_web  | 2023-06-08T20:45:24.432584311Z Migrating database
tandoor_web  | 2023-06-08T20:45:26.450027663Z Operations to perform:
tandoor_web  | 2023-06-08T20:45:26.450082108Z   Apply all migrations: account, admin, auth, authtoken, contenttypes, cookbook, oauth2_provider, sessions, sites, socialaccount
tandoor_web  | 2023-06-08T20:45:26.527355185Z Running migrations:
tandoor_web  | 2023-06-08T20:45:26.527416383Z   No migrations to apply.
tandoor_web  | 2023-06-08T20:45:27.034572871Z Generating static files
tandoor_web  | 2023-06-08T20:45:28.506843675Z js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
tandoor_web  | 2023-06-08T20:45:35.521872564Z 
tandoor_web  | 2023-06-08T20:45:35.521901500Z 1 static file copied to '/opt/recipes/staticfiles', 637 unmodified, 1352 post-processed.
tandoor_web  | 2023-06-08T20:45:35.662508695Z Done
tandoor_web  | 2023-06-08T20:45:35.852590798Z [2023-06-08 20:45:35 +0000] [1] [INFO] Starting gunicorn 20.1.0
tandoor_web  | 2023-06-08T20:45:35.853016537Z [2023-06-08 20:45:35 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
tandoor_web  | 2023-06-08T20:45:35.853041726Z [2023-06-08 20:45:35 +0000] [1] [INFO] Using worker: gthread
tandoor_web  | 2023-06-08T20:45:35.855856941Z [2023-06-08 20:45:35 +0000] [12] [INFO] Booting worker with pid: 12
tandoor_web  | 2023-06-08T20:45:35.930311718Z [2023-06-08 20:45:35 +0000] [13] [INFO] Booting worker with pid: 13
tandoor_web  | 2023-06-08T20:45:35.970239946Z [2023-06-08 20:45:35 +0000] [14] [INFO] Booting worker with pid: 14
```

**Comment by smilerz** [comment]
the issue is going to be at your reverse proxy not sending the right headers.  there are some examples [here ](https://docs.tandoor.dev/install/docker/)that might point you in the right direction on what you might be missing.

**Comment by kvnklk** [comment]
Used the example from the docs and only changed the `entrypoints` and `certresolver` to mine, looks like its working just fine, so in my case:

```
version: "3.9"

services:

  tandoor_db:
    restart: always
    container_name: tandoor_db
    image: postgres:14-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      default: null

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file: .env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./data/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - tandoor_db
    networks:
      default: null

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./data/mediafiles:/media:ro
    labels: # traefik example labels
      - "traefik.enable=true"
      - "traefik.http.routers.recipes.rule=Host(`recipes.domain.com`)"
      - "traefik.http.routers.recipes.entrypoints=websecure" # <--- Changed this
      - "traefik.http.routers.recipes.tls.certresolver=http_resolver" # <--- Changed this
    depends_on:
      - web_recipes
    networks:
      default: null
      proxy: null

### NETWORKS
networks:
  default:
  proxy:
    external: true

volumes:
  nginx_config:
  staticfiles:

```
