### ISSUE TITLE
Error uploading images to recipies

### ISSUE THREAD

**Issue by coolmule0** [TandoorRecipes/recipes#2540]
### Tandoor Version

1.5.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Bug description

Unable to upload an image for a recipe. It gives a pop-up notice in the website "There was an error updating a resource!"

It is a fresh install. No changes made to the .env file. 

### Relevant logs

```shell
The docker logs:


tandoor-nginx_recipes-1  | 2023-07-10T20:19:43.781350814Z 2023/07/10 20:19:43 [warn] 21#21: *56 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 192.168.1.136, server: localhost, request: "PUT /api/recipe/3/image/ HTTP/1.1", host: "192.168.1.34:8888", referrer: "http://192.168.1.34:8888/edit/recipe/internal/3/"
tandoor-nginx_recipes-1  | 2023-07-10T20:19:43.946816059Z 192.168.1.136 - - [10/Jul/2023:20:19:43 +0000] "PUT /api/recipe/3/image/ HTTP/1.1" 400 103 "http://192.168.1.34:8888/edit/recipe/internal/3/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" "-"
tandoor-web_recipes-1    | 2023-07-10T20:19:43.946755903Z 192.168.64.4 - - [10/Jul/2023:21:19:43 +0100] "PUT /api/recipe/3/image/ HTTP/1.0" 400 103 "http://192.168.1.34:8888/edit/recipe/internal/3/" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

The docker-compose file:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro
    #labels: # traefik example labels
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.recipes.rule=Host(`recipes.mydomain.com`, `recipes.myotherdomain.com`)"
    #  - "traefik.http.routers.recipes.entrypoints=web_secure" # your https endpoint
    #  - "traefik.http.routers.recipes.tls.certresolver=le_resolver" # your cert resolver
    ports:
      - 8888:80
    depends_on:
      - web_recipes
    networks:
      - default
      - t2_proxy

networks:
  default:
  t2_proxy: # This is your external traefik network
    external: true

volumes:
  nginx_config:
  staticfiles:
```
```
