### ISSUE TITLE
Access via Nginx Proxy Manager - CSRF error/no recipes displayed

### ISSUE THREAD

**Issue by johndoe0815** [TandoorRecipes/recipes#2581]
### Tandoor Version

1.5.4

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

My setup is:
Own domain managed in Cloudflare -> Nginx Proxy Manager as Add-On in Home Assistant OS -> Tandoor via Docker in a Proxmox Container.

Tandoor works without issues when accessing internally via IP (but only http, I have not understood if/how access via https is possible, as there is no option and the standard config seems to use only port 80).

When accessing via my domain, I got to the login screen, but after logging in I got a CSRF error. As discussed here (https://github.com/TandoorRecipes/recipes/issues/518), I could resolve that by using the environment variable CSRF_TRUSTED_ORIGINS with my exact domain as parameter. I could not find this variable mentioned in the docs or template file, I think it makes sense to add that.

Cloudflare is set to enforce https, and it seems to work that although I have pointed to http in NPM, it still opens tandoor via https according to the browser URL bar.
![grafik](https://github.com/TandoorRecipes/recipes/assets/92877294/1fbf18a0-a004-4741-98b9-86b79bd956da)

So login meanwhile works, but after that there are not recipes displayed at all, only placeholders:
![260034305-e5cc4bd4-42da-41dc-bc01-2575502e3ac3](https://github.com/TandoorRecipes/recipes/assets/92877294/cb0e2560-118b-4e24-992b-23b717a0fbb4)

This is what I see in the debug log:

```
Gunicorn Media: False
Sqlite: False
Debug: True

SERVER_PROTOCOL:HTTP/1.0
REMOTE_ADDR:172.11.1.4
SERVER_PORT:8080

HTTP_HOST:rezepte.mydomain.de
HTTP_CONNECTION:close
HTTP_X_FORWARDED_SCHEME:http
HTTP_X_FORWARDED_PROTO:http
HTTP_X_FORWARDED_FOR:147.155.254.155, 172.20.22.10
HTTP_X_REAL_IP:172.20.22.10
HTTP_USER_AGENT:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
HTTP_ACCEPT:text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
HTTP_ACCEPT_ENCODING:gzip
HTTP_ACCEPT_LANGUAGE:de,en-US;q=0.7,en;q=0.3
HTTP_CDN_LOOP:cloudflare
HTTP_CF_CONNECTING_IP:147.155.254.155
HTTP_CF_IPCOUNTRY:DE
HTTP_CF_RAY:7fer0daseer12bc5-FRA
HTTP_CF_VISITOR:{"scheme":"https"}
HTTP_CF_WARP_TAG_ID:3282c120-4999-484d-9999-d0fcaff28558
HTTP_COOKIE:cf_clearance=XXX; csrftoken=XXX
HTTP_DNT:1
HTTP_REFERER:https://rezepte.mydomain.de/search/
HTTP_SEC_FETCH_DEST:document
HTTP_SEC_FETCH_MODE:navigate
HTTP_SEC_FETCH_SITE:same-origin
HTTP_SEC_FETCH_USER:?1
HTTP_SEC_GPC:1
HTTP_UPGRADE_INSECURE_REQUESTS:1

wsgi.errors:<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f43ea926680>
wsgi.version:(1, 0)
wsgi.multithread:True
wsgi.multiprocess:True
wsgi.run_once:False
wsgi.file_wrapper:
wsgi.input_terminated:True
wsgi.input:<gunicorn.http.body.Body object at 0x7f43ea7111e0>
wsgi.url_scheme:http
```

Is this an http/https problem? 
If so, how is https being handled by tandoor?
I do not see any settings on this, the standard config also only uses port 80.
Cloudflared is set to force https and the login also works with that. Therefore also for the CSRF_TRUSTED_ORIGINS variable I maintained the https variable

**Comment by ignas2526** [comment]
Hi, I too use Nginx Proxy Manager. In the .env file try these values:
```
ALLOWED_HOSTS=rezepte.mydomain.de
CSRF_TRUSTED_ORIGINS=rezepte.mydomain.de
````
I found the CSRF_TRUSTED_ORIGINS in the source code. I personally don't have it set and everything works fine, but maybe it will help in your case.

Also, share your docker-compose.yml file.

In a meantime maybe you'll figure out the issue by trying out some stuff from my setup. In my case, both https and http with a custom domain work as well as from IP. I have `ALLOWED_HOSTS=192.168.28.11,recipes.mydomain.de`. I use MacVLAN, so ignore the `mac_address` and lack of  `ports`. Also note that I'm using external Postgres, so ignore the database part. I avoid running extra nginx proxy for the static files by passing them to the NPM and serving them from there (`recipes_staticfiles` and `recipes_mediafiles`).

The Tandoor recipes docker-compose.yml file:
```
version: "3"
services:

  web_recipes:
    restart: unless-stopped
    image: vabene1111/recipes:1.4.8
    env_file:
      - ./.env
    volumes:
      - recipes_staticfiles:/opt/recipes/staticfiles
      - recipes_nginx_config:/opt/recipes/nginx/conf.d
      - recipes_mediafiles:/opt/recipes/mediafiles
    deploy:
      resources:
          limits:
            cpus: '0.5'
    mac_address: 02:42:ac:11:02:01
    networks:
      my_docker_net:
        ipv4_address: 192.168.28.11

volumes:
  recipes_nginx_config:
    external: true
  recipes_staticfiles:
    external: true
  recipes_mediafiles:
    external: true

networks:
  my_docker_net:
    external: true
```
The NPM docker-compose.yml file
```
version: '3.8'

services:
  app:
    image: 'jc21/nginx-proxy-manager:2.10.2'
    restart: unless-stopped
    volumes:
      - /var/docker/containers/reverse_proxy/data:/data
      - /var/docker/containers/reverse_proxy/letsencrypt:/etc/letsencrypt
      ######################################
      # static files from other containers #
      ######################################
      
      # recipes
      - recipes_staticfiles:/static_files/recipes/static:ro
      - recipes_mediafiles:/static_files/recipes/media:ro

    mac_address: 02:42:ac:11:01:01
    networks:
      my_docker_net:
        ipv4_address: 192.168.28.1

networks:
  my_docker_net:
    external: true

volumes:
  recipes_staticfiles:
    external: true
  recipes_mediafiles
    external:true
```

In NPM, in the recipes proxy host, under the Advanced I have the following:
```
location /media/* {
  internal;
  alias /static_files/recipes/media/;
  autoindex off;
}

location /static/* {
  internal;
  alias /static_files/recipes/static/;
  autoindex off;
}
```

**Comment by johndoe0815** [comment]
Thanks for helping out!

This is my docker-compose file, I basically did not change anything in the standard file from the official setup guide:

```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - stack.env

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - stack.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 80:80
    env_file:
      - stack.env
    depends_on:
      - web_recipes
    volumes:
      # Do not make this a bind mount, see https://docs.tandoor.dev/install/docker/#volumes-vs-bind-mounts
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - ./mediafiles:/media:ro

volumes:
  nginx_config:
  staticfiles:
```

Same applies for the environment variables, just took over the template:
```
DEBUG=1
SQL_DEBUG=0
DEBUG_TOOLBAR=0
ALLOWED_HOSTS=*
SECRET_KEY=randomkeys
TIMEZONE=Europe/Berlin
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=morerandomkeys
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
CSRF_TRUSTED_ORIGINS=rezepte.mydomain.de
```

With ALLOWED_HOSTS=* I would expect that I do not need to put in specific urls at the moment.
In CSRF_TRUSTED_ORIGINS I removed the https://, same behaviour as before.
As I also do not see anything http/https related in your config, I still do not understand why access via direct IP is only possible via http for me, but for you also via https?!
