### ISSUE TITLE
Requests to /api keep failing with code 403

### ISSUE THREAD

**Issue by Trivernis** [TandoorRecipes/recipes#2673]
### Issue

I am running a k8s cluster and applied the k8s configurations (with slight modifications so they fit my setup).
In that setup I'm using an external load balancer (by hetzner) to direct requests to traefik which then passes it to the recipe-service that exposes the two ports 8080 and 80. Requests to `static` and `media` get directed to port 80 and everything else to port 8080.
Registering the initial user and logging in worked fine but the UI won't load or create any recipes, food items, etc.
In the network tab I was able to see that all Requests to `/api` endpoints fail with status code 403 and response `{"detail":"Authentication credentials were not provided."}`. 
All these requests seem to not pass the `cookie` header to the api endpoint. 

My assumption is that something in the configuration of the proxies might prevent cookies from being sent to the api endpoint.

The setup configuration can be found [here](https://github.com/Trivernis/cluster-config/tree/main/apps/tandoor/app)

### Tandoor Version

1.5.6

### OS Version

1x LatestArch, 2x Fedora 38

### Setup

Kubernetes

### Reverse Proxy

Traefik

### Environment file

```shell
- name: DEBUG
            value: "0"
          - name: ALLOWED_HOSTS
            value: "*"
          - name: CSRF_TRUSTED_ORIGINS
            value: "https://recipes.trivernis.dev"
          - name: GUNICORN_MEDIA
            value: "0"
```

**Comment by Trivernis** [comment]
I fixed it by setting the `X-Forwarded-Proto` header to `https` explicitly

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: tandoor-headers
  namespace: tandoor
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: https
```
