### ISSUE TITLE
Issues when trying to backup with pg_dumpall for postgres upgrade

### ISSUE THREAD

**Issue by maxbrueckl** [TandoorRecipes/recipes#2782]
### Issue

As the support of Postgres version <= 11 was dropped, I started the update progress. I ran
```sh
docker exec -it recipes_db pg_dumpall -U djangouser > ~/tandoor.sql
```
on my existing database. The resulting tandoor.sql looks like this:
```sql
--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE djangouser;
ALTER ROLE djangouser WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'XXXXXXXX';






\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 11.22
-- Dumped by pg_dump version 11.22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

pg_dump: [archiver (db)] query failed: ERROR:  could not identify an ordering operator for type oid
LINE 1: ...ssid = 'pg_extension'::regclass AND deptype = 'e' ORDER BY 3
                                                                      ^
HINT:  Use an explicit ordering operator or modify the query.
pg_dump: [archiver (db)] query was: SELECT classid, objid, refobjid FROM pg_depend WHERE refclassid = 'pg_extension'::regclass AND deptype = 'e' ORDER BY 3
pg_dumpall: pg_dump failed on database "djangodb", exiting
```

Any idea how I can proceed?

### Tandoor Version

1.5.10

### OS Version

Ubuntu 22.04.3

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Environment file

```env
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=1
SQL_DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=XXXX

# random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
# ---------------------------- REQUIRED -------------------------
SECRET_KEY=XXXX
# ---------------------------------------------------------------

# your default timezone See https://timezonedb.com/time-zones for a list of timezones
# TIMEZONE=Europe/Berlin

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql
# DB_OPTIONS= {} # e.g. {"sslmode":"require"} to enable ssl
POSTGRES_HOST=recipes_db
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
# ---------------------------- REQUIRED -------------------------
POSTGRES_PASSWORD=XXXXX
# ---------------------------------------------------------------
POSTGRES_DB=djangodb

# database connection string, when used overrides other database settings.
# format might vary depending on backend
# DATABASE_URL = engine://username:password@host:port/dbname

# the default value for the user preference 'fractions' (enable/disable fraction support)
# default: disabled=0
FRACTION_PREF_DEFAULT=0

# the default value for the user preference 'comments' (enable/disable commenting system)
# default comments enabled=1
COMMENT_PREF_DEFAULT=1

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# Default for user setting sticky navbar
# STICKY_NAV_PREF_DEFAULT=1

# If base URL is something other than just / (you are serving a subfolder in your proxy for instance http://recipe_app/recipes/)
# Be sure to not have a trailing slash: e.g. '/recipes' instead of '/recipes/'
# SCRIPT_NAME=/recipes

# If staticfiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly, MUST END IN /
# this is not required if you are just using a subfolder
# This can either be a relative path from the applications base path or the url of an external host
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0

# S3 Media settings: store mediafiles in s3 or any compatible storage backend (e.g. minio)
# as long as S3_ACCESS_KEY is not set S3 features are disabled
# S3_ACCESS_KEY=
# S3_SECRET_ACCESS_KEY=
# S3_BUCKET_NAME=
# S3_REGION_NAME= # default none, set your region might be required
# S3_QUERYSTRING_AUTH=1 # default true, set to 0 to serve media from a public bucket without signed urls
# S3_QUERYSTRING_EXPIRE=3600 # number of seconds querystring are valid for
# S3_ENDPOINT_URL= # when using a custom endpoint like minio

# Email Settings, see https://docs.djangoproject.com/en/3.2/ref/settings/#email-host
# Required for email confirmation and password reset (automatically activates if host is set)
# EMAIL_HOST=
# EMAIL_PORT=
# EMAIL_HOST_USER=
# EMAIL_HOST_PASSWORD=
# EMAIL_USE_TLS=0
# EMAIL_USE_SSL=0
# DEFAULT_FROM_EMAIL= # email sender address (default 'webmaster@localhost')
# ACCOUNT_EMAIL_SUBJECT_PREFIX= # prefix used for account related emails (default "[Tandoor Recipes] ")

# allow authentication via reverse proxy (e.g. authelia), leave off if you dont know what you are doing
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
# when unset: 0 (false)
REMOTE_USER_AUTH=0

# Default settings for spaces, apply per space and can be changed in the admin view
# SPACE_DEFAULT_MAX_RECIPES=0 # 0=unlimited recipes
# SPACE_DEFAULT_MAX_USERS=0 # 0=unlimited users per space
# SPACE_DEFAULT_MAX_FILES=0 # Maximum file storage for space in MB. 0 for unlimited, -1 to disable file upload.
# SPACE_DEFAULT_ALLOW_SHARING=1 # Allow users to share recipes with public links

# allow people to create accounts on your application instance (without an invite link)
# when unset: 0 (false)
ENABLE_SIGNUP=1

# If signup is enabled you might want to add a captcha to it to prevent spam
# HCAPTCHA_SITEKEY=
# HCAPTCHA_SECRET=

# if signup is enabled you might want to provide urls to data protection policies or terms and conditions
# TERMS_URL=
# PRIVACY_URL=
# IMPRINT_URL=

# enable serving of prometheus metrics under the /metrics path
# ATTENTION: view is not secured (as per the prometheus default way) so make sure to secure it
# trough your web server (or leave it open of you dont care if the stats are exposed)
# ENABLE_METRICS=0

# allows you to setup OAuth providers
# see docs for more information https://vabene1111.github.io/recipes/features/authentication/
SOCIAL_PROVIDERS=allauth.socialaccount.providers.openid_connect
SOCIALACCOUNT_PROVIDERS = { "openid_connect": { "SERVERS": [ { "id": "authelia", "name": "Authelia", "server_url": "https://XXXX/.well-known/openid-configuration", "token_auth_method": "client_secret_basic", "APP": { "client_id": "tandoor", "secret": "XXXXXX", }, } ] }}

# Should a newly created user from a social provider get assigned to the default space and given permission by default ?
# ATTENTION: This feature might be deprecated in favor of a space join and public viewing system in the future
# default 0 (false), when 1 (true) users will be assigned space and group
SOCIAL_DEFAULT_ACCESS = 1

# if SOCIAL_DEFAULT_ACCESS is used, which group should be added
SOCIAL_DEFAULT_GROUP = admin

# Django session cookie settings. Can be changed to allow a single django application to authenticate several applications
# when running under the same database
# SESSION_COOKIE_DOMAIN=.example.com
# SESSION_COOKIE_NAME=sessionid # use this only to not interfere with non unified django applications under the same top level domain

# by default SORT_TREE_BY_NAME is disabled this will store all Keywords and Food in the order they are created
# enabling this setting makes saving new keywords and foods very slow, which doesn't matter in most usecases.
# however, when doing large imports of recipes that will create new objects, can increase total run time by 10-15x
# Keywords and Food can be manually sorted by name in Admin
# This value can also be temporarily changed in Admin, it will revert the next time the application is started
# This will be fixed/changed in the future by changing the implementation or finding a better workaround for sorting
# SORT_TREE_BY_NAME=0

# LDAP authentication
# default 0 (false), when 1 (true) list of allowed users will be fetched from LDAP server
#LDAP_AUTH=
#AUTH_LDAP_SERVER_URI=
#AUTH_LDAP_BIND_DN=
#AUTH_LDAP_BIND_PASSWORD=
#AUTH_LDAP_USER_SEARCH_BASE_DN=

# Enables exporting PDF (see export docs)
# Disabled by default, uncomment to enable
ENABLE_PDF_EXPORT=1
```

### Docker-Compose file
```yaml
  # Tandoor - Recipes
  recipes_db:
    <<: *common-keys-apps # See EXTENSION FIELDS at the top
    image: postgres:11-alpine
    container_name: recipes_db
    volumes:
      - $APPDATADIR/postgresql:/var/lib/postgresql/data
    env_file: ./recipes.env
    environment:
      <<: *environment-tz-puid-pgid
#      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
#    secrets:
#      - postgres_password
    networks:
      - recipes

  recipes_web:
    <<: *common-keys-apps-privileged # See EXTENSION FIELDS at the top
    image: vabene1111/recipes
    container_name: recipes_web
    volumes:
      - $APPDATADIR/recipes/staticfiles:/opt/recipes/staticfiles
      - $APPDATADIR/recipes/nginx_config:/opt/recipes/nginx/conf.d
      - $APPDATADIR/recipes/mediafiles:/opt/recipes/mediafiles
    env_file: ./recipes.env
    environment:
      <<: *environment-tz-puid-pgid
    depends_on:
      - recipes_db
    networks:
      - recipes

  recipes_nginx:
    <<: *common-keys-apps-privileged # See EXTENSION FIELDS at the top
    image: nginx:mainline-alpine
    container_name: recipes_nginx
    volumes:
      - $APPDATADIR/recipes/nginx_config:/etc/nginx/conf.d:ro
      - $APPDATADIR/recipes/staticfiles:/static
      - $APPDATADIR/recipes/mediafiles:/media
    env_file:
      - ./recipes.env
    environment:
      <<: *environment-tz-puid-pgid
    labels: # traefik example labels
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.recipes-rtr.entrypoints=https"
      - "traefik.http.routers.recipes-rtr.rule=Host(`recipes.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.recipes-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.recipes-rtr.service=recipes-svc"
      - "traefik.http.services.recipes-svc.loadbalancer.server.port=80"
    depends_on:
      - recipes_web
    networks:
      - t2_proxy
      - recipes
```

### Relevant logs

Log from database container:

```
2023-12-05 12:09:52.074 CET [534] ERROR:  could not identify an ordering operator for type oid at character 119

2023-12-05 12:09:52.074 CET [534] HINT:  Use an explicit ordering operator or modify the query.

2023-12-05 12:09:52.074 CET [534] STATEMENT:  SELECT classid, objid, refobjid FROM pg_depend WHERE refclassid = 'pg_extension'::regclass AND deptype = 'e' ORDER BY 3
```
