### ISSUE TITLE
Superuser can't access the action menu (3 vertical dots) on any recipe

### ISSUE THREAD

**Issue by pascalxricher** [TandoorRecipes/recipes#2863]
### Tandoor Version

Dec 3 commit abf8f791360b2bc4a5c7d011877668679bcbb3f2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Others (please state below)

### Other

Login Portal (Synology Reverse Proxy)

### Bug description

I installed Tandoor using Portainer (docker-compose), and the installation completed successfully. When I access Tandoor for the first time, I get asked to create a superuser, which I do.

The authentication with the superuser credentials is then successful, and I can create a new recipe using the dropdown menu in the top banner. The recipe gets created without a problem.

I can then search for the recipe, and access it, no problem... **Once in the recipe, I don't have access to the "three vertical dots" (I don't see it) to edit or delete the newly created recipe**.

If I access to the Users menu, in the Admin feature, I can see that this user is active, and is flagged as a superuser.

Any idea what it could be ?

**docker-compose**
```
version: "3.9"
services:
  tandoor:
    image: vabene1111/recipes:latest
    container_name: Tandoor
    hostname: tandoor
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
    user: 1026:100
    volumes:
      - /volume1/docker/tandoor/staticfiles:/opt/recipes/staticfiles
      - /volume1/docker/tandoor/mediafiles:/opt/recipes/mediafiles
      - /volume1/docker/tandoor/nginx:/opt/recipes/nginx/conf.d
    env_file:
      - stack.env
    restart: always

  nginx:
    image: nginx:mainline-alpine
    container_name: Tandoor-NGINX
    hostname: nginx-tandoor
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1
    volumes:
      - /volume1/docker/tandoor/staticfiles:/static:ro
      - /volume1/docker/tandoor/mediafiles:/media:ro
      - /volume1/docker/tandoor/nginx:/etc/nginx/conf.d:ro
    ports:
      - 9815:80
    env_file:
      - stack.env
    restart: always
```
**NGINX tandoor.conf**
```
server {
  listen 80;
  server_name localhost;

  client_max_body_size 128M;

  # serve media files
  location /media/ {
    alias /media/;
  }
  # pass requests for dynamic content to gunicorn
  location / {
    proxy_set_header Host $http_host;
    proxy_pass http://tandoor:8080;

    error_page 502 /errors/http502.html;
  }

  location /errors/ {
    alias /etc/nginx/conf.d/errorpages/;
    internal;
  }
}
```
**Environment variables**
```
DEBUG=0
SQL_DEBUG=0
ALLOWED_HOSTS=
SECRET_KEY=my-32-caracters-string
TIMEZONE=America/Montreal
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=192.168.86.40
POSTGRES_PORT=2665
POSTGRES_USER=tandoor
POSTGRES_PASSWORD=my-db-password
POSTGRES_DB=tandoor
FRACTION_PREF_DEFAULT=0
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
GUNICORN_MEDIA=0
REVERSE_PROXY_AUTH=0
ENABLE_PDF_EXPORT=1
EXPORT_FILE_CACHE_DURATION=600
```
