### ISSUE TITLE
Recipe import fails Server Error (500)

### ISSUE THREAD

**Issue by Buddinski88** [TandoorRecipes/recipes#2867]
### Tandoor Version

1.5.5

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

When I try to create a new recipe, the save fails with an Server Error (500).
An import works partially, but not completely.
It's about this recipe: https://www.chefkoch.de/rezepte/2908231443105223/Puten-Lauch-Pfanne.html

My docker-compose.yml looks like this:
```yaml
version: '3.9'
services:
  db_recipes:
    container_name: tandoor-db
    image: postgres:11-alpine
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file: 
      - local.env

  web_recipes:
    container_name: tandoor-webservice
    image: vabene1111/recipes:1.5.5
    restart: unless-stopped
    networks:
      - traefik_proxy
    volumes:
      - mediafiles:/opt/recipes/mediafiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - staticfiles:/opt/recipes/staticfiles
    depends_on:
      - db_recipes
    env_file:
      - local.env

  nginx_recipes:
    container_name: tandoor-ngnix
    image: nginx:mainline-alpine
    restart: unless-stopped
    networks:
      - traefik_proxy
    env_file:
      - local.env
    labels: # traefik example labels
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tandoor-rtr.entrypoints=https"
      - "traefik.http.routers.tandoor-rtr.rule=Host(`tandoor.$DOMAINNAME`)"
      - "traefik.http.routers.tandoor-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.tandoor-rtr.middlewares=chain-no-auth@file" # For No Authentication
      ## HTTP Services
      #- "traefik.http.routers.tandoor-rtr.service=tandoor-svc"
      #- "traefik.http.services.tandoor-svc.loadbalancer.server.port=80"
    volumes:
      - mediafiles:/media:ro
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
    depends_on:
      - web_recipes

networks:
  traefik_proxy:
    external: true

volumes:
  mediafiles:
  nginx_config:
  postgresql:
  staticfiles:
```

### Relevant logs

```shell
07.01.2024
16:17:06
2024-01-07 15:17:06.613 UTC [1] LOG:  database system is ready to accept connections
07.01.2024
16:18:19
2024-01-07 15:18:19.530 UTC [41] ERROR:  null value in column "show_ingredients_table" violates not-null constraint
07.01.2024
16:18:19
2024-01-07 15:18:19.530 UTC [41] DETAIL:  Failing row contains (96, , 0, , 0, f, null, 1, null, null, null).
07.01.2024
16:18:19
2024-01-07 15:18:19.530 UTC [41] STATEMENT:  INSERT INTO "cookbook_step" ("name", "instruction", "time", "order", "file_id", "show_as_header", "search_vector", "step_recipe_id", "space_id") VALUES ('', '', 0, 0, NULL, false, NULL, NULL, 1) RETURNING "cookbook_step"."id"
```
