### ISSUE TITLE
1.5.11 HTTP Server Error 500 (downgrade solves issue)

### ISSUE THREAD

**Issue by nicedevil007** [TandoorRecipes/recipes#2893]
### Tandoor Version

1.5.11

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

I updated my environment on docker compose with the following docker compose file:

```yaml
---
version: "3.9"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    container_name: tandoor_db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/backup
    environment:
      TIMEZONE: Europe/Berlin
      POSTGRES_PORT: 5432
      POSTGRES_USER: ###########
      POSTGRES_PASSWORD: ###########
      POSTGRES_DB: djangodb
  web_recipes:
    restart: always
    image: vabene1111/recipes:latest
    container_name: tandoor_web
    environment:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: ###########
      TZ: Europe/Berlin
      DB_ENGINE: django.db.backends.postgresql
      POSTGRES_HOST: db_recipes
      POSTGRES_PORT: 5432
      POSTGRES_USER: ###########
      POSTGRES_PASSWORD: ###########
      POSTGRES_DB: djangodb
      FRACTION_PREF_DEFAULT: 1
      COMMENT_PREF_DEFAULT: 1
      SHOPPING_MIN_AUTOSYNC_INTERVAL: 5
      EMAIL_HOST: ###########
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ###########
      EMAIL_HOST_PASSWORD: ###########
      EMAIL_USE_TLS: 1
      EMAIL_USE_SSL: 0
      DEFAULT_FROM_EMAIL: ###########
      ACCOUNT_EMAIL_SUBJECT_PREFIX: "###########"
      ENABLE_SIGNUP: 1
      ENABLE_PDF_EXPORT: 1
      SOCIAL_DEFAULT_ACCESS: 0
      SORT_TREE_BY_NAME: 1
      GUNICORN_MEDIA: 0
      DEBUG: 0
      DISABLE_TREE_FIX_STARTUP: 1
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    container_name: tandoor_nginx
    ports:
      - 8070:80
    depends_on:
      - web_recipes
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - ./staticfiles:/static:ro
      - ./mediafiles:/media:ro
volumes:
  nginx_config: null
  staticfiles: null
  mediafiles: null
  postgresql: null
networks: {}
```

It doesn't matter if I use local IP or DNS to access the IP.
If I use the tag on the docker image to revert back to 1.5.10 everything works.

```java
    image: vabene1111/recipes:1.5.10
```

### Relevant logs

This leads instant to the error:
![image](https://github.com/TandoorRecipes/recipes/assets/17103076/690a711b-78ad-4c7f-a908-c210dd3bfc98)

**Comment by smilerz** [comment]
please provide logs

**Comment by anytimesoon** [comment]
This has happened to me also. Logs posted below. I can't see anything odd in them, though

```
[2024-01-19 23:42:51 +0100] [1] [INFO] Starting gunicorn 20.1.0
[2024-01-19 23:42:51 +0100] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2024-01-19 23:42:51 +0100] [1] [INFO] Using worker: gthread
[2024-01-19 23:42:51 +0100] [12] [INFO] Booting worker with pid: 12
[2024-01-19 23:42:51 +0100] [13] [INFO] Booting worker with pid: 13
[2024-01-19 23:42:51 +0100] [14] [INFO] Booting worker with pid: 14
192.168.16.3 - - [19/Jan/2024:23:42:55 +0100] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:55 +0100] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:55 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:56 +0100] "GET /favicon.ico HTTP/1.1" 404 6346 "https://recipes.delartigue.xyz/accounts/login/?next=/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:58 +0100] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:58 +0100] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:59 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:42:59 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:43:03 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:43:09 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:43:32 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:43:35 +0100] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:43:35 +0100] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:43:35 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:22 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:27 +0100] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:27 +0100] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:28 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:32 +0100] "GET /search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"
192.168.16.3 - - [19/Jan/2024:23:44:33 +0100] "GET /favicon.ico HTTP/1.1" 500 145 "https://recipes.delartigue.xyz/search/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"
192.168.16.3 - - [19/Jan/2024:23:44:35 +0100] "GET /service-worker.js HTTP/1.1" 500 145 "https://recipes.delartigue.xyz/service-worker.js" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"
192.168.16.3 - - [19/Jan/2024:23:44:42 +0100] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:44 +0100] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
192.168.16.3 - - [19/Jan/2024:23:44:44 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

**Comment by smilerz** [comment]
is debug enabled?  have you tried clearing the browser cache?

**Comment by danieljkemp** [comment]
I've got the same thing here. Looks like I was hit by this AND the keycloak allauth deprecation  (with no breaking change in the patch notes, :( )

So I was trying to debug two things at once it turns out.

Nothing notable in the logs with debug turned on. The curious bit is, once I reset my django admin pass and fixed the OIDC config, a browser with an old session was functional, but a browser that had never logged in, and a private session both gave the 500 error and landed me here.

**Comment by vabene1111** [comment]
I did not mean to deprecated anything, must have been something in the changelog of django all Auth that I missed. Will take a look later

**Comment by danieljkemp** [comment]
Sorry for the passive aggressive response the culprit is
mentioned in
https://github.com/TandoorRecipes/recipes/pull/2706

FWIIW their changes make sense, and updating auth libraries is always a good idea in general was just cuag off guard and had to go digging

Only an issue if already using Keycloak specifically, swapping was easier than I thought, but this 500 error bug made me think the oauth switch wasn't working

**Comment by nicedevil007** [comment]
So does that mean you got it up an working again @danieljkemp? I don't use keycloak but I had Authentik in the past but I disabled it maybe 6-9 months ago.

**Comment by danieljkemp** [comment]
Keycloak works with the openid_connect allauth plugin. But currently only in a tab that previously had a valid session due to the above bug?

Private browser session and it gives the 500 as above and I haven't seen why in the logs (with debug on).

But hey at least I am 80% sure that keycloak is working right ;)

**Comment by smilerz** [comment]
> Keycloak works with the openid_connect allauth plugin. But currently only in a tab that previously had a valid session due to the above bug?
> 
> 
> 
> Private browser session and it gives the 500 as above and I haven't seen why in the logs (with debug on).
> 
> 
> 
> But hey at least I am 80% sure that keycloak is working right ;)

Keycloak was deprecated in the allauth library.

**Comment by vabene1111** [comment]
Ok so has this been resolved? I cannot really help here since for me the update works fine and without any debug logs I cant see any error. 

If you are still having issues please set `DEBUG=1` in your `.env` and post the logs here when making the request.

**Comment by danieljkemp** [comment]
> Ok so has this been resolved? I cannot really help here since for me the update works fine and without any debug logs I cant see any error.
> 
> If you are still having issues please set `DEBUG=1` in your `.env` and post the logs here when making the request.

@anytimesoon @nicedevil007 Are you folks using OIDC plugins? I am still seeing the issue after updating keycloak to use OIDC directly in allauth. In a session with existing cookies the page loads with no errors, but it throws the 500 in a session without a session. 

I don't get much from the debug logs. Things fail before they can hit an oauth provider at all
```
[2024-01-22 14:37:22 +0100] [7] [DEBUG] GET /
172.30.3.27 - - [22/Jan/2024:14:37:22 +0100] "GET / HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
[2024-01-22 14:37:22 +0100] [7] [DEBUG] GET /search/
172.30.3.27 - - [22/Jan/2024:14:37:22 +0100] "GET /search/ HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
[2024-01-22 14:37:22 +0100] [7] [DEBUG] GET /accounts/login/
172.30.3.27 - - [22/Jan/2024:14:37:22 +0100] "GET /accounts/login/?next=/search/ HTTP/1.1" 500 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
[2024-01-22 14:37:22 +0100] [7] [DEBUG] GET /favicon.ico
172.30.3.27 - - [22/Jan/2024:14:37:22 +0100] "GET /favicon.ico HTTP/1.1" 404 6370 "https://recipes.especiallyrelative.net/accounts/login/?next=/search/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
```

This is all I get in the debug logs, nothing is seen from the keycloak side, the browser does not show any requests other than these either.

**Comment by anytimesoon** [comment]
I'm not using any special auth service. Just whatever is provided by tandoor. So, I don't think this was related to auth in my case.

I dont have access to my laptop this week, so can't help much more than that at the moment, I'm afraid. 

If this issue is ongoing next week, I'll chime in again. Sorry about that

**Comment by nicedevil007** [comment]
I removed the OIDC part with authentik months ago, I guess more than 2-3 Updates are gone since that.
Here is my output of the webgui after enabling debug=1

```html
<html>
<body>
<!--StartFragment--><h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ProgrammingError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">column cookbook_space.space_theme does not exist
LINE 1: ...kbook_space"."name", "cookbook_space"."image_id", "cookbook_...
                                                             ^
</pre>
Request Method: | GET
-- | --
https://rezepte.glaeser-it.de/
4.2.7
ProgrammingError
column cookbook_space.space_theme does not exist LINE 1: ...kbook_space"."name", "cookbook_space"."image_id", "cookbook_...                                                              ^
/opt/recipes/venv/lib/python3.10/site-packages/django/db/backends/utils.py, line 89, in _execute
cookbook.views.views.index
/opt/recipes/venv/bin/python
3.10.13
['/opt/recipes',  '/opt/recipes/venv/bin',  '/usr/local/lib/python310.zip',  '/usr/local/lib/python3.10',  '/usr/local/lib/python3.10/lib-dynload',  '/opt/recipes/venv/lib/python3.10/site-packages']
Mon, 22 Jan 2024 21:30:32 +0100

<!--EndFragment-->
</body>
</html>
```

**Comment by nicedevil007** [comment]
Sure, have to restore a backup right now because I'm testing other stuff as well.

I just took the whole compose and created a complete new environment, deleted the old one, all volumes deleted etc.
Again, this was/is my docker-compose.yaml

```yaml
version: "3.9"
services:
  db_recipes:
    restart: always
    image: postgres:15-alpine
    container_name: tandoor_db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/backup
    environment:
      - TZ=${TZ}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  web_recipes:
    restart: always
    image: vabene1111/recipes:1.5.11
    container_name: tandoor_web
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - TZ=${TZ}
      - DB_ENGINE=${DB_ENGINE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FRACTION_PREF_DEFAULT=${FRACTION_PREF_DEFAULT}
      - COMMENT_PREF_DEFAULT=${COMMENT_PREF_DEFAULT}
      - SHOPPING_MIN_AUTOSYNC_INTERVAL=${SHOPPING_MIN_AUTOSYNC_INTERVAL}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - ACCOUNT_EMAIL_SUBJECT_PREFIX=${ACCOUNT_EMAIL_SUBJECT_PREFIX}
      - ENABLE_SIGNUP=${ENABLE_SIGNUP}
      - ENABLE_PDF_EXPORT=${ENABLE_PDF_EXPORT}
      - SOCIAL_DEFAULT_ACCESS=${SOCIAL_DEFAULT_ACCESS}
      - SORT_TREE_BY_NAME=${SORT_TREE_BY_NAME}
      - GUNICORN_MEDIA=${GUNICORN_MEDIA}
      - DEBUG=${DEBUG}
      - DISABLE_TREE_FIX_STARTUP=${DISABLE_TREE_FIX_STARTUP}
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    container_name: tandoor_nginx
    ports:
      - 8070:80
    depends_on:
      - web_recipes
    volumes:
      - ./nginx_config:/etc/nginx/conf.d:ro
      - ./staticfiles:/static:ro
      - ./mediafiles:/media:ro
volumes:
  nginx_config: null
  staticfiles: null
  mediafiles: null
  postgresql: null
networks: {}
```

this one the .env file for this stack:

```yaml
ALLOWED_HOSTS="*"
SECRET_KEY=###############
TZ=Europe/Berlin
DB_ENGINE=django.db.backends.postgresql
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangouser
POSTGRES_PASSWORD=###############
POSTGRES_DB=djangodb
FRACTION_PREF_DEFAULT=1
COMMENT_PREF_DEFAULT=1
SHOPPING_MIN_AUTOSYNC_INTERVAL=5
EMAIL_HOST=###############
EMAIL_PORT=587
EMAIL_HOST_USER=###############
EMAIL_HOST_PASSWORD=###############
EMAIL_USE_TLS=1
EMAIL_USE_SSL=0
DEFAULT_FROM_EMAIL=###############
ACCOUNT_EMAIL_SUBJECT_PREFIX="###############"
ENABLE_SIGNUP=1
ENABLE_PDF_EXPORT=1
SOCIAL_DEFAULT_ACCESS=0
SORT_TREE_BY_NAME=1
GUNICORN_MEDIA=0
DEBUG=1
DISABLE_TREE_FIX_STARTUP=1
```

This leads to a not accessible webui at all. I can't even do the normal localipadress:port stuff to get access to it.
docker ends with this:

```
tandoor_web    |   Applying oauth2_provider.0001_initial... OK
tandoor_web    |   Applying oauth2_provider.0002_auto_20190406_1805... OK
tandoor_web    |   Applying oauth2_provider.0003_auto_20201211_1314... OK
tandoor_web    |   Applying oauth2_provider.0004_auto_20200902_2022... OK
tandoor_web    |   Applying oauth2_provider.0005_auto_20211222_2352... OK
tandoor_web    |   Applying oauth2_provider.0006_alter_application_client_secret... OK
tandoor_web    |   Applying oauth2_provider.0007_application_post_logout_redirect_uris... OK
tandoor_web    |   Applying sessions.0001_initial... OK
tandoor_web    |   Applying sites.0001_initial... OK
tandoor_web    |   Applying sites.0002_alter_domain_unique... OK
tandoor_web    |   Applying socialaccount.0001_initial... OK
tandoor_web    |   Applying socialaccount.0002_token_max_lengths... OK
tandoor_web    |   Applying socialaccount.0003_extra_data_default_dict... OK
tandoor_web    |   Applying socialaccount.0004_app_provider_id_settings... OK
tandoor_web    |   Applying socialaccount.0005_socialtoken_nullable_app... OK
tandoor_web    |   Applying socialaccount.0006_alter_socialaccount_extra_data... OK
tandoor_web    | Generating static files
tandoor_web    | js-reverse file written to /opt/recipes/cookbook/static/django_js_reverse
tandoor_web    | 
tandoor_web    | 649 static files copied to '/opt/recipes/staticfiles', 1705 post-processed.
tandoor_web    | Done
tandoor_web    | [2024-01-22 21:44:33 +0100] [1] [INFO] Starting gunicorn 20.1.0
tandoor_web    | [2024-01-22 21:44:33 +0100] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
tandoor_web    | [2024-01-22 21:44:33 +0100] [1] [INFO] Using worker: gthread
tandoor_web    | [2024-01-22 21:44:33 +0100] [14] [INFO] Booting worker with pid: 14
tandoor_web    | [2024-01-22 21:44:34 +0100] [15] [INFO] Booting worker with pid: 15
tandoor_web    | [2024-01-22 21:44:34 +0100] [16] [INFO] Booting worker with pid: 16
```

I will post docker stuff from the previous installation in a few minutes, this here was all done with a fresh new installation
