### ISSUE TITLE
Recipe ingredient/step checks

### ISSUE THREAD

**Issue by cgiacofei** [TandoorRecipes/recipes#2985]
### Is your feature request related to a problem? Please describe.

The ability to check-off ingredients in the recipe view is great, but there is a bit of an accessibility issue with the implementation. Being red/green colorblind it is nearly impossible to tell the difference between the 2 states.

### Describe the solution you'd like

The ideal solution I see would be to modify the text to add a strike-through when it is checked.

**Comment by vabene1111** [comment]
I see, will try to remember this when reworking the interface

**Comment by tomtjes** [comment]
@cgiacofei a workaround would be custom css.
```css
.text-primary::before {
    color: yellow;
}

.text-success::before {
    color: blue;
}
```

Put this in a file called `custom.css` or similar, upload it at `your-site.xyz/list/user-file/` and select it as a custom theme in space settings.
