### ISSUE TITLE
Truenas Scale Electric Eel can't only nginx is ever visible

### ISSUE THREAD

**Issue by lzinga** [TandoorRecipes/recipes#3524]
### Issue

I have been attempting to install tandoor within my TrueNAS Scale (Electric Eel version specifically which supports docker) and I only ever get the nginx splash screen. It won't show any actual content. I have provided my compose file and hope this is something simple that I am missing. I used the file referenced in the truenas portainer installation and modified it to not use the .env file.

As an alternative note, since truenas has an application dashboard it would be cool if tandoor was included as an app that could be installed with a lot of the default settings configured for you. (https://www.truenas.com/docs/truenasapps/usingcustomapp/)

### Tandoor Version

Latest

### OS Version

Truenas Scale Electric Eel 24.10.1

### Setup

Docker / Docker-Compose

### Reverse Proxy

No reverse proxy

### Environment file

```shell

```

### Docker-Compose file

```shell
services:
  db_recipes:
    environment:
      - POSTGRES_DB=tandoor
      - POSTGRES_USER=tandoor
      - POSTGRES_PASSWORD=[password]
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /mnt/HDDs/Applications/tandoor/data:/var/lib/postgresql/data
  nginx_recipes:
    depends_on:
      - web_recipes
    image: nginx:mainline-alpine
    ports:
      - '8777:80'
    restart: always
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - /mnt/HDDs/Applications/tandoor/staticfiles:/static:ro
      - /mnt/HDDs/Applications/tandoor/media:/media:ro
  web_recipes:
    depends_on:
      - db_recipes
    environment:
      - SECRET_KEY=[key]
      - DB_ENGINE=django.db.backends.postgresql
      - DEBUG=0
      - POSTGRES_HOST=db_recipes
      - POSTGRES_DB=tandoor
      - POSTGRES_PORT=5432
      - POSTGRES_USER=tandoor
      - ALLOWED_HOSTS=*
      - POSTGRES_PASSWORD=[password]
    image: vabene1111/recipes
    restart: unless-stopped
    volumes:
      - /mnt/HDDs/Applications/tandoor/staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - /mnt/HDDs/Applications/tandoor/media:/opt/recipes/mediafiles
volumes:
  nginx_config
```

### Relevant logs

```shell

```

**Comment by swofl** [comment]
A bit late, so I don't know if your issue is still current, but I have it running fine under TrueNAS Scale. Maybe it's your bind mount of staticfiles?

Here is my config

```yml
services:
  db_recipes:
    environment:
      - SECRET_KEY=xxx
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_DB=djangodb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=xxx
    image: postgres:16-alpine
    restart: always
    volumes:
      - /mnt/docker/tandoor/database:/var/lib/postgresql/data
  nginx_recipes:
    depends_on:
      - web_recipes
    image: nginx:mainline-alpine
    ports:
      - '5555:80'
    restart: always
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - /mnt/docker/tandoor/mediafiles:/media:ro
  web_recipes:
    depends_on:
      - db_recipes
    environment:
      - ALLOWED_HOSTS=my.cool.domain
      - DB_ENGINE=django.db.backends.postgresql
      - DEBUG=0
      - POSTGRES_HOST=db_recipes
      - POSTGRES_DB=djangodb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=xxx
      - SECRET_KEY=xxx
    image: vabene1111/recipes:1.5.31
    restart: always
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - /mnt/docker/tandoor/mediafiles:/opt/recipes/mediafiles
volumes:
  nginx_config: Null
  staticfiles: Null
```
