### ISSUE TITLE
SMTP seemingly not working

### ISSUE THREAD

**Issue by AlexKalopsia** [TandoorRecipes/recipes#3537]
### Tandoor Version

1.5.31

### Setup

Docker / Docker-Compose

### Reverse Proxy

SWAG

### Bug description

I have setup the email env variables according to my [SMTP provider docs](https://login.inleed.net/helpcenter/596/mail-client-settings-imap-smtp-pop), and yet I fail to get verification emails. 

The result is that I get a "Confirmation email sent to myemail@gmail.com. " popup message, but there is no email to be found (I also checked the spam folder). 

Please keep in mind that Tandoor works fine otherwise, stores data and media correctly, and that these same values work fine for other containers and I do regularly get emails from other services. 

```
EMAIL_HOST=nsX.inleed.net
EMAIL_PORT=465
EMAIL_HOST_USER=noreply@mydomain.com
EMAIL_HOST_PASSWORD=XXXXXXXXXXXXXXXX
EMAIL_USE_TLS=1
EMAIL_USE_SSL=1
DEFAULT_FROM_EMAIL=noreply@mydomain.com
ACCOUNT_EMAIL_SUBJECT_PREFIX="[Tandoor] "
```

I am not sure what to do, because the logs seemingly don't print any information re SMTP. I have also tried setting `EMAIL_USE_SSL=0`, but with that setup I don't even get a success popup message. 

My docker compose: 

```
  tandoor-db:
    restart: always
    container_name: tandoor-db
    image: postgres:16-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - docker_default

  tandoor:
    image: vabene1111/recipes
    container_name: tandoor
    restart: unless-stopped
    ports:
      - 8073:8080
    env_file:
      - ./.env
    environment:
      - UID=${PUID}
      - GID=${PGID}
      - TZ=${TZ} 
    volumes:
      - ./static:/opt/recipes/staticfiles
      - ./media:/opt/recipes/mediafiles
    depends_on:
      - tandoor-db
    networks:
      - docker_default
```

Let me know if you have any input 🙏 

### Relevant logs

```shell

```
