### ISSUE TITLE
Home Assistant Add-on

### ISSUE THREAD

**Issue by gullygossner** [TandoorRecipes/recipes#354]
I'm not sure if you are familiar with Home Assistant or not but I feel like this would make a great add-on within HA.

I believe there is a way to make docker containers add-ons within Home Assistant, I am just not well versed enough with docker to be able to complete this myself.

**Comment by vabene1111** [comment]
i actually use home assistant myself and really like it so yes, this is a great idea. 

I have no idea how difficult it would be to implement, i definitly need to find a way to configure the environment variables but apart from that it should not be to hard i hope.

**Comment by vabene1111** [comment]
ok it appears to be easy to create an addon https://developers.home-assistant.io/docs/add-ons/

But it also appears that there is more to it than just throwing in a docker compose for more complex applications https://github.com/hassio-addons/addon-grafana/tree/main

one could obviously use sqlite and gunicorn webserving, that would probably eliminate the need for anything complex

**Comment by gullygossner** [comment]
That's completely fair, I have no idea what the complexities are to this stuff but just figured I'd pose the question. I may try firing it in docker I'm just worried about a port overlap or something borking my home assistant instance which is higher priority for me to have running.

**Comment by tdvantine** [comment]
I would love to see a meal plan add on.

**Comment by hillbicks** [comment]
Came here looking whether this is already being discussed, although my focus would be different. 

I think there are plenty of users, who are using home assistant on a tablet in the kitchen. So while having an addon for HA would be great, I think the bigger benefit would be to have some sort of a tandoor card that can display recipes stored in tandoor and can be interacted with. Administration can be in tandoor itself, use the tandoor card only for usage with touch friendly design. 

Create a page with an overview of the recipes, click on it and it takes you to the detailed steps. Touch friendly buttons to mark and hide the completed steps and automatically start a timer for steps, which have a timer configured. 

In my opinion, that would be a fanatastic addition to HA and it would be a unique feature of tandoor, something to set yourself apart.

Anyway, great app. Keep it up!

**Comment by tdvantine** [comment]
Reading that made me think that with the right settings you might be able to get an iFrame to work...not saying it would be pretty or anything, but it could get ya by until a real plugin is made by the community or vabene. I my self may look into that.

**Comment by IxsharpxI** [comment]
i really hope to see this come to light. would be a great addition

**Comment by vabene1111** [comment]
Basically allow the recipe view to live in an i frame that is responsive enough to scale correctly to the home assistant card 🤔 
i guess that would be really nice.
Obviously installing in home assistant would be even better but that seems to be a bit of work to get it working

**Comment by zacps** [comment]
I'm really interested in adding timers as mentioned by @hillbicks, even if just in the webpage. 

@vabene1111 do you have any opinions on how you'd like this to be implemented?

**Comment by vabene1111** [comment]
i guess timer would be quite simple to add into the recipe view (which is already migrated to the new vue.js component system)

There is a small modal in the time field which might be used. One would have too see if the current system which can simply add minutes to the step is sufficient or if something more in depth is needed.

Timers could also be included in the text using the templating engine ...

**Comment by zacps** [comment]
Ok thanks, I'll try to have a look at this soon. No promises on timing though so don't let that stop anyone else that wants to take it on.

**Comment by simeonradivoev** [comment]
Just adding an [IFrame Panel](https://www.home-assistant.io/integrations/panel_iframe/) works great. The only gotchas are that you need it to be running in HTTPS and if using a reverse proxy you need to allow modify your x-frame options.

**Comment by tdvantine** [comment]
What do you need to modify as far as those xframe options?

**Comment by tdvantine** [comment]
@simeonradivoev would you mind just posting your nginx conf? (assuming you are using nginx for the reverse proxy) I am rewritting the manual instal guide and trying to nail down the best nginx setup.

**Comment by simeonradivoev** [comment]
```
location / {
	proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
	proxy_pass http://web_recipes:8080;
	proxy_hide_header X-Frame-Options;
    }
```

The `proxy_hide_header X-Frame-Options;` is the key.

**Comment by simeonradivoev** [comment]
The biggest issue is you have to expose the recipes to the world. Not sure if there is a way for a home assistant to serve a website from its local network and display it. I guess that's where a plugin might comee in.

**Comment by tdvantine** [comment]
Could run it locally then reverse proxy it.

**Comment by simeonradivoev** [comment]
How can you not expose a recipes website that needs to be shown in an IFrame in an exposed Home Assistant? 
Wouldn't the recipes website need to be accessible from the outside, to also be accessible from an IFrame in an exposed home assistant?

**Comment by JamesDAdams** [comment]
we can not activate the iframe without adding an nginx container ? i use directly traefik with recipes

**Comment by vabene1111** [comment]
i think the server needs to allow i frame embedding. This might be possible with traefik but if not, adding the nginx back into the loop will not cause any harm so might as well do that

**Comment by JamesDAdams** [comment]
> i think the server needs to allow i frame embedding. This might be possible with traefik but if not, adding the nginx back into the loop will not cause any harm so might as well do that

I would like to avoid adding a container just for that ^^

**Comment by nliakm** [comment]
Hi, in case someone also has recipes running on kubernetes. This is how my ingressroute (i use traefik) looks like to allow having the iframe load inside home-assistant:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/enable: "true"
    hajimari.io/icon: "chef-hat"
  name: recipes
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rezepte.${SECRET_DOMAIN}`) && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: recipes-headers
      services:
        - kind: Service
          name: recipes
          namespace: default
          port: 8080
    - match: Host(`rezepte.${SECRET_DOMAIN}`) && PathPrefix(`/media`)
      kind: Rule
      middlewares:
        - name: recipes-headers
      services:
        - kind: Service
          name: recipes
          namespace: default
          port: 80
    - match: Host(`rezepte.${SECRET_DOMAIN}`) && PathPrefix(`/static`)
      kind: Rule
      middlewares:
        - name: recipes-headers
      services:
        - kind: Service
          name: recipes
          namespace: default
          port: 80
  tls:
    secretName: "recipes-tls-secret"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: recipes-headers
  namespace: default
spec:
  headers:
    customResponseHeaders:
      X-Frame-Options: ""
```
