### ISSUE TITLE
Missing recipe images after update

### ISSUE THREAD

**Issue by Wiz0r** [TandoorRecipes/recipes#3591]
### Tandoor Version

1.5.32

### Setup

Others (please state below)

### Reverse Proxy

No reverse proxy

### Other

Cosmos Cloud (Docker)

### Bug description

After the update to version 1.5.32, all recipes have lost their images in both the overview and recipe views.

I checked my file system inside and outside of Docker, and everything appears to be in order. The images are still present in the folder .../mediafiles/recipes, where they should be. Also the filename of the images matches with the stored files.

Nevertheless the debug information in Chrome shows a 404 "not found" error for all images.

Someone has an idea what is going wrong?

### Relevant logs

```shell

```

**Comment by Wiz0r** [comment]
Btw, downgrading to 1.5.31 fully solves the problem.

**Comment by vabene1111** [comment]
that is very strange 🤔 can you enable DEBUG in the `.env` file and see if there are any logs indicating any kind of error?

**Comment by Wiz0r** [comment]
I reinstalled 1.5.32 and now some of the images are there: 
![Image](https://github.com/user-attachments/assets/33046045-db0b-46d7-8c93-a62d25319429)

In 1.5.31 i can open the Image-links manually in the Browser. 

The same link is not opening 1.5.32 manually and the error looks like this:
![Image](https://github.com/user-attachments/assets/03849eaf-3ee2-4823-a436-1f4472bf2878)

I use [@cosmos](https://github.com/azukaar/Cosmos-Server) as Docker App Manager. I am currently not shure how use .env files there. What I can do is editing the docker-compose.yaml.

**Comment by Wiz0r** [comment]
I did some further investigations and tests and probably found the solution to my problem.

Completely emptying the browser cache after the update to 1.5.32 make all images appear normally again.

**Comment by Wiz0r** [comment]
I found the posibility to add "DEBUG=1" to the environment of the docker container. The DEBUG option was currently not integrated into the config.

Strangely, all images are visible again afterwards even in 1.5.32.  I still have images in 1.5.32 when setting DEBUG to 0 or delete it completely again.

**Comment by vabene1111** [comment]
images showing in the next version for a time might be due to caching. Still its pretty strange that the links work but images are not displayed. I will need to verify on my test instance

**Comment by nollm** [comment]
I use tandoor as docker container behind Nginx Proxy Manager.

```
services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - /share/Container/tandoor-recipes/postgresql:/var/lib/postgresql/data
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=djangodb

  web_recipes:
    restart: always
    image: vabene1111/recipes
    ports:
      - 8081:8080
    volumes:
      - /share/Container/tandoor-recipes/staticfiles:/opt/recipes/staticfiles
      - /share/Container/tandoor-recipes/mediafiles:/opt/recipes/mediafiles
    environment:
      - SECRET_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=djangodb
    depends_on:
      - db_recipes
```

This is my dev console when I open the recipes page.

![Image](https://github.com/user-attachments/assets/6e1ed291-7754-4b97-8b88-2cfdf60c80c6)
