### ISSUE TITLE
[Guide] The Ultimate Tandoor Configuration for Docker Swarm/Standalone With Traefik Reverse Proxy

### ISSUE THREAD

**Issue by CodeBradley** [TandoorRecipes/recipes#3605]
### Documentation link

https://docs.tandoor.dev/install/docker/

### Affected section

Installation

### Issue description

Yeah, I totally click-baited the title. I can't say with certainty this is the best setup for Docker/Traefik, but I can tell you I've been reading through the documentation, GitHub issues, etc. and after a hell of a time trying to get this to work I now have my instance working perfectly. If you want to avoid a bunch of CSRF, Invalid Scheme and broken image issues then you should use this configuration. It will save you a ton of headaches.

tandoor-stack.yml
> I'm using this with Portainer which is why I can use .env variables in my stack file. If you aren't using Portainer, then you will need to use actual values or precompile the environment variables. This should be very simple to tweak for standalone instances if you understand the differences between swarm and standalone compose files.

```yaml
version: "3.9"

services:
  db_recipes:
    image: postgres:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    volumes:
      - /mnt/storage/docker/services/tandoor/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    networks:
      - default

  web_recipes:
    image: vabene1111/recipes:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=db_recipes
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOWED_HOSTS=${SUBDOMAIN}.${DOMAIN}
      - CSRF_TRUSTED_ORIGINS=https://${SUBDOMAIN}.${DOMAIN},https://${SUBDOMAIN}.${DOMAIN}
      - TZ=${TZ}
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - nginx_config:/opt/recipes/nginx/conf.d
      - /mnt/storage/docker/services/tandoor/media:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default

  nginx_recipes:
    image: nginx:mainline-alpine
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      labels: 
        - "traefik.enable=true"
        # Modify this accordingly
        - "traefik.http.routers.tandoor-router.tls=true"
        - "traefik.http.routers.tandoor-router.entrypoints=web,websecure"
        - "traefik.http.routers.tandoor-router.middlewares=https-redirect@file"
        - "traefik.http.routers.tandoor-router.rule=Host(`${SUBDOMAIN}.${DOMAIN}`)"
        - "traefik.http.routers.tandoor-router.tls.certresolver=${CERTRESOLVER}"
        - "traefik.http.services.tandoor-router.loadbalancer.server.port=80"
        - "traefik.http.middlewares.tandoor-headers.headers.customrequestheaders.Host=${SUBDOMAIN}.${DOMAIN}"
        - "traefik.http.middlewares.tandoor-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
    volumes:
      - nginx_config:/etc/nginx/conf.d:ro
      - staticfiles:/static:ro
      - /mnt/storage/docker/services/tandoor/media:/media:ro
    depends_on:
      - web_recipes
    networks:
      - default
      - traefik_proxy

networks:
  default:
  traefik_proxy:
    external: true

volumes:
  nginx_config:
  staticfiles:
```

/etc/nginx/conf.d/Recipes.conf
> Start the container and add this to `/var/lib/docker/volumes/tandor-stack_nginx_config/_data`, or wherever your volume directory is at. Alternatively, you can add add a bind mount but you might need to restart the container. One thing I haven't tested yet is if this change persists when the container gets moved to another node in Swarm mode. If this happens, I plan to just have a bind mount bound to Recipes.conf directly (otherwise the error config get overwritten)
```nginx
server {

    if ($host = recipes.example.com) { 
        return 301 https://$host$request_uri;
    }

    server_name recipes.example.com;
    listen 80;
    return 404;

}
server {

    server_name recipes.example.com;
    listen 443 ssl;
    client_max_body_size 128M;

    ssl_certificate /etc/letsencrypt/live/recipes.example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/recipes.example.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://web_recipes:8080;  
        proxy_redirect http://web_recipes:8080 https://recipes.example.com; 
        error_page 502 /errors/http502.html;
    }

    location /media/ {
        alias /media/;
        add_header Content-Disposition 'attachment; filename="$args"';
    }

    location /errors/ {
        alias /etc/nginx/conf.d/errorpages/;
        internal;
    }

}
```
This doesn't use a ton of resources, but I also want to say that I think this stack is a good Sablier candidate so that it only uses server resources when you actually need to use it.
