### ISSUE TITLE
Uploading images returns Fehler beim Aktualisieren but images still upload

### ISSUE THREAD

**Issue by Svagtlys** [TandoorRecipes/recipes#3638]
### Tandoor Version

Tandoor 2 alpha

### Setup

Docker / Docker-Compose

### Reverse Proxy

Caddy

### Bug description

When I go to upload images through the web UI on Tandoor 2 alpha release, I receive a pop up error "Fehler beim Aktualisieren". My localization should be English and the rest of the UI is in English, so this also seems to be a bug.

The main bug is that there doesn't actually seem to be any issues with the image upload- if I leave the recipe I see the new image as the main image, and entering the recipe shows the new image. I checked in the server files and also see the images in /mediafiles (though they have the same name as the image I uploaded, which seems like it could lead to interfering file names down the line, so maybe that's the error?).

### Relevant logs

```shell

```

**Comment by vabene1111** [comment]
can you please set `DEBUG=1` in your env and send me the browser and server logs of when this happens? Makes it much easier for me to debug

**Comment by Svagtlys** [comment]
[tandoorimagesavecontainerlogs.txt](https://github.com/user-attachments/files/19666454/tandoorimagesavecontainerlogs.txt)

[tandoorimagesavebrowserlogs.txt](https://github.com/user-attachments/files/19666456/tandoorimagesavebrowserlogs.txt)

Here are the logs from the steps of uploading the file and clicking save on the recipe (I think). Let me know if you need more.

In case this is some weird permissions issue without having permission issues, I'm running tandoor with the following permissions changes. I haven't noticed any issues so far (besides the django_js_reverse permission issue fixed by mapping the folder to a bind mount with permissions), but I've only been running Tandoor like this for a couple of days
```yaml
#----- Security box -----
    user: "${UID}"
    cap_drop:
      - all
    security_opt:
      - no-new-privileges=true
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
#-------------------------------
```
