### ISSUE TITLE
Alpha 2 - Worker failed to boot

### ISSUE THREAD

**Issue by Flo-R1der** [TandoorRecipes/recipes#3675]
### Tandoor Version

2.0.0-alpha-2

### Setup

Docker / Docker-Compose

### Reverse Proxy

Nginx Proxy Manager (NPM)

### Bug description

When trying to start tandoor with the `2.0.0-alpha-2` tag, the container throws a couple of traceback and exit on code 3: [_tandoor_logs.txt](https://github.com/user-attachments/files/19915384/_tandoor_logs.txt)

here's my compose-stack (Portainer) for reference which is running on a RaspberryPi 4B with Debian 11 LTS (arm64):
``````
version: "3"

services:
  db:
    restart: always
    image: postgres:16-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - stack.env

  app:
    #restart: always
    image: vabene1111/recipes:2.0.0-alpha-2
    container_name: tandoor
    dns: 
      - 192.168.178.1
    ports:
      - 5003:8080
    env_file:
      - stack.env
    volumes:
      #- ./staticfiles:/opt/recipes/staticfiles
      - ./staticfiles-vue3:/opt/recipes/staticfiles
      #- ./nginx_config:/opt/recipes/nginx/conf.d
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db
``````
As you can see, I let the container recreate the staticfiles. Started multiple times with the same directory, old directory and empty staticfiles directory, but still the same issue.

### Relevant logs

```shell

```

**Comment by Rhodds** [comment]
Hello,

It still doesn't work for me but at least it starts :), but since you are using Docker, some libraries are missing.  
To fix this, you will need to create a custom **Dockerfile**:

```dockerfile
FROM ghcr.io/tandoorrecipes/recipes:2.0.0-alpha-2

RUN apk update && apk add libgcc
```

Then, update your docker-compose.yaml to use the build context instead of the image:

```yaml
build:
  context: .
# image: ghcr.io/tandoorrecipes/recipes:2.0.0-alpha-2
```

Finally, start the containers with:
```bash
docker compose up --build (-d)
```
The `-d` flag is optional if you want to run it in detached mode.
