### ISSUE TITLE
Importer allows changes to ingredients that cannot be persisted

### ISSUE THREAD

**Issue by agross** [TandoorRecipes/recipes#3722]
### Tandoor Version

9419a823e2bc40ea22c519f745c46b30cb0c4af9

### Setup

Docker / Docker-Compose

### Reverse Proxy

Traefik

### Bug description

```
Fehler beim Erstellen - (400)

Errors:
    - steps.0.ingredients.3.unit.name: This field may not be blank.
    - steps.0.ingredients.4.unit.name: This field may not be blank.
```

<img width="439" alt="Image" src="https://github.com/user-attachments/assets/7e2dd69c-54cf-4af4-be27-e9ba7e84aef4" />

### Relevant logs

```shell

```
