### ISSUE TITLE
Server Error (500) when using basic search 

### ISSUE THREAD

**Issue by kampsj** [TandoorRecipes/recipes#428]
### Version
Version: 0.14.2 (just upgraded my docker installation)

### Bug description
Using the basic search results in a Server Error (500) message. I can still, however, use the advance search to search using ingredients or tags. Searching for nothing does not produce an error message. 

Below are two relevant log lines, though they do not seem helpful.
```
web_recipes_1    | 172.21.0.2 - - [19/Feb/2021:17:18:47 +0000] "GET /search/?csrfmiddlewaretoken=x8JX4l7ImHixYYZTMcRgJFfnKYqgFrbmjLmCe88yFE3xP3IJuNNPwFtBWiJBSSJh&name=kaas&internal=unknown HTTP/1.0" 500 145 "http://rolodex.mand/search/" "Mozilla/5.0 (Android 9; Mobile; rv:87.0) Gecko/87.0 Firefox/87.0"

nginx_recipes_1  | 172.21.0.1 - - [19/Feb/2021:17:18:47 +0000] "GET /search/?csrfmiddlewaretoken=x8JX4l7ImHixYYZTMcRgJFfnKYqgFrbmjLmCe88yFE3xP3IJuNNPwFtBWiJBSSJh&name=kaas&internal=unknown HTTP/1.1" 500 145 "http://rolodex.mand/search/" "Mozilla/5.0 (Android 9; Mobile; rv:87.0) Gecko/87.0 Firefox/87.0" "192.168.1.141"
```

**Comment by vabene1111** [comment]
is there nothing else in the logs when running `docker-compose logs -f` ?

What is your setup (compose, env, ...) ?

**Comment by kampsj** [comment]
I'm running Tandoor with docker. My compose and .env file are listed below. Both files are hardly modified from the ones you provided (I added an extra volume and changed some passwords). 
I tried upgrading my installation with both an older backup (one I made before a previous upgrade) and the latest. Both give a 500 error when searching. 

I checked the logs again, and below are the only entries when performing a search:
```web_recipes_1    | 2021-02-20T11:16:35.103535589Z 172.21.0.2 - - [20/Feb/2021:11:16:35 +0000] "GET /search/?csrfmiddlewaretoken=PgriO2FhjZ6MWRToPTaMihPjL4reGE3OsDKQtnc3Q08qzkkgCYmqolnleHcOzY0P&name=b&internal=unknown HTTP/1.0" 500 145 "http://192.168.1.16:8080/search/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0"
nginx_recipes_1  | 2021-02-20T11:16:35.357843072Z 192.168.1.3 - - [20/Feb/2021:11:16:35 +0000] "GET /favicon.ico HTTP/1.1" 499 0 "http://192.168.1.16:8080/search/?csrfmiddlewaretoken=PgriO2FhjZ6MWRToPTaMihPjL4reGE3OsDKQtnc3Q08qzkkgCYmqolnleHcOzY0P&name=b&internal=unknown" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0" "-"
```


docker-compose.yml:
```
version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
      - ./db_backup:/opt/recipes/db_backup
    depends_on:
      - db_recipes

  nginx_recipes:
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/static
      - ./mediafiles:/media
      - ./db_backup:/db_backup
```

.env:
```
# only set this to true when testing/debugging
# when unset: 1 (true) - dont unset this, just for development
DEBUG=0

# hosts the application can run under e.g. recipes.mydomain.com,cooking.mydomain.com,...
ALLOWED_HOSTS=*

# random secret key, use for example base64 /dev/urandom | head -c50 to generate one
SECRET_KEY=[redacted]

# add only a database password if you want to run with the default postgres, otherwise change settings accordingly
DB_ENGINE=django.db.backends.postgresql_psycopg2
POSTGRES_HOST=db_recipes
POSTGRES_PORT=5432
POSTGRES_USER=djangodb
POSTGRES_PASSWORD=[boop]
POSTGRES_DB=djangodb

# Users can set a amount of time after which the shopping list is refreshed when they are in viewing mode
# This is the minimum interval users can set. Setting this to low will allow users to refresh very frequently which
# might cause high load on the server. (Technically they can obviously refresh as often as they want with their own scripts)
SHOPPING_MIN_AUTOSYNC_INTERVAL=5

# If staticfiles are stored at a different location uncomment and change accordingly
# STATIC_URL=/static/

# If mediafiles are stored at a different location uncomment and change accordingly
# MEDIA_URL=/media/

# Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
# provided that include an additional nxginx container to handle media file serving.
# If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
# when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
GUNICORN_MEDIA=0


# allow authentication via reverse proxy (e.g. authelia), leave of if you dont know what you are doing
# docs: https://github.com/vabene1111/recipes/tree/develop/docs/docker/nginx-proxy%20with%20proxy%20authentication
# when unset: 0 (false)
REVERSE_PROXY_AUTH=0


# the default value for the user preference 'comments' (enable/disable commenting system)
# when unset: 1 (true)
COMMENT_PREF_DEFAULT=1
```
[Pastebin, GitHub forma](https://pastebin.com/ra3iAuLR)
